### PR TITLE
IQSS/11095- Account for multivalue needed by cvoc scripts

### LINKED ISSUE #11095: External CVoc - indexing can fail for single valued fields
**What steps does it take to reproduce the issue?** Configuring a CVoc script on a field that is not multivalued will fail if the script is configured to add more than one value to the index, i.e. it adds both the identifier and a name, or includes translations. An example would be using the [depositorOrcid](https://github.com/gdcc/dataverse-external-vocab-support/blob/main/examples/config/depositorOrcid.json) example :CVocConf setting.

* When does this issue occur? When an identifier (vs a free text entry) is entered.

* Which page(s) does it occurs on?
dataset page

* What happens?
indexing fails

* To whom does it occur (all users, curators, superusers)?
all

* What did you expect to happen?

**Which version of Dataverse are you using?**
develop/6.5+

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?
Yes

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: This PR changes the /api/admin/index/solr/schema output to correctly indicate that a field should be multivalued when it is the term-uri field of an external controlled vocabulary config. (Note the format of the output/etc. is not changed, just the content - same as if a metadatablock were editing to make a field multivalued.)

**Which issue(s) this PR closes**:

- Closes #11095

**Special notes for your reviewer**:

**Suggestions on how to test this**:  Configure the ORCID script on the depositor field as described in the issue, test that indexing doesn't work now, works after the update and updating the solr schema/restarting solr.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**: included

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/api/Index.java [hunk 1]
```diff
@@ -474,7 +475,7 @@ public String getSolrSchema() {
                  */
                 logger.info("email type detected (" + nameSearchable + ") See also https://github.com/IQSS/dataverse/issues/759");
             }
-            String multivalued = datasetField.getSolrField().isAllowedToBeMultivalued().toString();
+            String multivalued = Boolean.toString(datasetFieldType.getSolrField().isAllowedToBeMultivalued()|| cvocTermUriMap.containsKey(datasetFieldType.getId()));
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/api/Index.java:478]:
```suggestion
            String multivalued = Boolean.toString(datasetFieldType.getSolrField().isAllowedToBeMultivalued() || cvocTermUriMap.containsKey(datasetFieldType.getId()));
```

**Review by pdurbin — COMMENTED** [review]
I haven't run the code but I assume this is a no-op if a developer were to recreate the schema.xml file using the process I'm suggesting developers follow in this pull request (please take a look):

- #11024

That is, it's a no-op because we don't ship any sort of cvoc config out of the box. It's a feature that installations opt-in to.

I'm almost ready to send this to QA (test are passing: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-11096/1/testReport/ ) but I did leave a few tiny suggestions.

**Comment by qqmyers** [comment]
Yes it's a no-op, but if Dataverse ever does ship with some external cvoc scripts registered, the right thing to do would be to run update-fields.sh on an instance with those scripts configured - so consistent with #11024.

**Review by pdurbin — APPROVED** [review]
