### PR TITLE
7056 Skip unknown types in a dataset which cause the whole dataset to…

### LINKED ISSUE #7056: Unknown types in a dataset causes the whole dataset to fail from being harvested
When the issue occurs: When harvesting using dataverse_json and there's custom types like "titulo" or "mraCollection"
Which page it occurs on: Harvesting Dashboard
To whom it occurs: People who harvest using dataverse_json
Version: 4.20

image

### PR DESCRIPTION
**Pull request by JingMa87**
… fail from being harvested

**What this PR does / why we need it**: Makes datasets with unknown types harvestable using dataverse_json

**Which issue(s) this PR closes**: 7056

Closes #7056 

**Special notes for your reviewer**: Good fix

**Suggestions on how to test this**: Harvest the Princeton_Authored_Datasets OAI set from the harvard repo using dataverse_json. Without this fix you will get 267 successful harvest and 2 fails. With the fix you will harvest all 269 datasets. The controversial datasets are https://dataverse.harvard.edu/api/datasets/export?exporter=dataverse_json&persistentId=doi:10.7910/DVN/B6OJKG and https://dataverse.harvard.edu/api/datasets/export?exporter=dataverse_json&persistentId=doi:10.7910/DVN/I5O6OS.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: No

**Is there a release notes update needed for this change?**: I think it's an important change for harvesting from another dataverse.

**Additional documentation**: N/A

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java [hunk 1]
```diff
@@ -1,23 +1,7 @@
...
-import edu.harvard.iq.dataverse.DatasetFieldType;
-import edu.harvard.iq.dataverse.DatasetFieldValue;
-import edu.harvard.iq.dataverse.DatasetVersion;
-import edu.harvard.iq.dataverse.Dataverse;
-import edu.harvard.iq.dataverse.DataverseContact;
-import edu.harvard.iq.dataverse.DataverseTheme;
-import edu.harvard.iq.dataverse.FileMetadata;
-import edu.harvard.iq.dataverse.MetadataBlockServiceBean;
-import edu.harvard.iq.dataverse.TermsOfUseAndAccess;
+import edu.harvard.iq.dataverse.*;
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java:4]: I mentioned this in a review on another pull request but we favor using the full import statement instead of wildcards.

File: src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java [hunk 2]
```diff
@@ -566,7 +553,8 @@ public DatasetField parseField(JsonObject json, Boolean testType) throws JsonPar
     
 
         if (type == null) {
-            throw new JsonParseException("Can't find type '" + json.getString("typeName", "") + "'");
+            logger.info("Can't find type '" + json.getString("typeName", "") + "'");
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java:556]: Is this going to happen a lot? If so, should it be reduced from "info" to "fine" so it doesn't clutter the logs?

**Comment by jggautier** [comment]
> We've never promoted using the dataverse_json format for harvesting (I believe DDI is preferred) but this should make it more possible to use it.

Maybe not in the guides but I've promoted it to reduce information loss and most of the harvesting Harvard Dataverse does from other Dataverse installations is using dataverse_json. I would think that DDI Codebook would be preferred if all metadata could be mapped to it, but that's probably going to be less and less true with increasing support for other standards.

File: src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java (hunk 1 above)
Comment (JingMa87) [reply src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java:4]: I'll reverse the change, my Intellij automatically does this. Super nice feature though otherwise.

File: src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java (hunk 2 above)
Comment (JingMa87) [reply src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java:556]: @pdurbin This'll happen potentially multiple thousands of times when doing a harvesting run on a big OAI set for the first time. So I'll just change it to "fine".

File: src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java (hunk 1 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java]: Yeah, I've heard that about Intellij. Thanks for reversing the change.

**Comment by kcondon** [comment]
@JingMa87 I am still seeing the two failures.

**Comment by JingMa87** [comment]
> @JingMa87 I am still seeing the two failures.
> 
> ```
> <record>
>   <date>2020-07-10T16:28:10</date>
>   <millis>1594398490946</millis>
>   <sequence>8513</sequence>
>   <logger>edu.harvard.iq.dataverse.harvest.client.HarvesterServiceBean.kc0605202020-07-10T16-27-22</logger>
>   <level>SEVERE</level>
>   <class>edu.harvard.iq.dataverse.harvest.client.HarvesterServiceBean</class>
>   <method>logGetRecordException</method>
>   <thread>187</thread>
>   <message>Exception processing getRecord(), oaiUrl=https://dataverse.harvard.edu/oai, identifier=doi:10.7910/DVN/B6OJKG, edu.harvard.iq.dataverse.api.imports.ImportException, Failed to import harvested dataset: class edu.harvard.iq.dataverse.engine.command.exception.CommandException (Command [DatasetCreate dataset:20721] failed: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/collection1: ERROR: [doc=dataset_20721] unknown field 'mraCollection')</message>
> </record>
> ```

@kcondon I can't reproduce the error. I've looked into the DatasetCreate Command but without the actual error happening it's like looking for a needle in a haystack. Are you on the latest version with the latest changes? What happens if you re-run the harvest, does it work the second time?

**Comment by kcondon** [comment]
@JingMa87 I have run it again and still see the failures. Running it again just results in 0 harvested, 0 failed. Looks like failures do are not harvested again.

**Comment by JingMa87** [comment]
@kcondon I pushed all my changes to the branch already. What if you delete the harvesting client, add it again and re-run, do you still get the issue?

**Comment by kcondon** [comment]
Yes, I have done that several times, every time I test. You could add debug code and I could run a harvest to see what it thinks it is doing.
________________________________

**Comment by JingMa87** [comment]
Does this query in the database return something for you? If so, this row is not supposed to be there and stops the field type mraCollection from being filtered out by my code change. Then, it gets passed to Solr and the error happens.
`SELECT * FROM public.datasetfieldtype where name = 'mraCollection';`

I've looked into adding debugging code, but the class where the error happens (CreateHarvestedDatasetCommand) is a whole big mess of polymorphism, generics and interfaces gone wrong. When I use the debugger, I can't inspect the execute() function of that Command where the error happens so I'm relegating to reading the code. Hopefully this helps.

**Comment by kcondon** [comment]
@JingMa87 Yes, that sql query returns a record. Why do you say it should not be there? Also, wouldn't you have seen the same record in your own test? I understand about the code complexity. I was thinking about a lower tech debugging of adding debug logging if that helps.

**Comment by JingMa87** [comment]
@kcondon I'll make a new ticket for clients that do have the field in the DB and will try to fix that in the coming days.
