### PR TITLE
fix facet and title display with &apos; in the value

### LINKED ISSUE #11737: presentation of encoded apostophes
**What steps does it take to reproduce the issue?**

Switch on facets for contributor name, create datasets with either a title or contributor name containing  `&apos;`. An example with both in a single dataset  https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/MF7UWA

* When does this issue occur?

  Some metadata field value contains  `&amp;apos;`

* Which page(s) does it occurs on?

  Dataset page, search result page.

* What happens?

  In some occasions `&amp;apos;` is properly shown as `'` in other occasions ugly as `&apos;`, see screenshots.

* To whom does it occur (all users, curators, superusers)?

  all

* What did you expect to happen?

  Almost always see `'`

**Which version of Dataverse are you using?**

It happens on 6.5 as well as 6.7.1

**Any related open or closed issues to this bug report?**

**Screenshots:**

Header line is not OK Image

Search result is not OK Image

Search result with match is OK Image

Metadata is OK Image

Facet is not OK Image

**Are you thinking about creating a pull request for this issue?**

Yes

### PR DESCRIPTION
**Pull request by jo-pol**
**What this PR does / why we need it**:

Indirectly apply `MarkupChecker.stripAllTags` to presented data

**Which issue(s) this PR closes**:

- Closes #11737

**Special notes for your reviewer**:

**Suggestions on how to test this**:

See #11737
After deploy re-index the datasets with the `&apos;` values to make the facets appear properly.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

No

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/DatasetPage.java [hunk 1]
```diff
@@ -1649,6 +1651,15 @@ public void setDisplayCitation(String displayCitation) {
         this.displayCitation = displayCitation;
     }
 
+    public String getDisplayTitle() {
+        //displayCitation = dataset.getCitation(false, workingVersion);
+        return displayTitle;
+    }
+
+    public void setDisplayTitle(String displayCitation) {
+        this.displayCitation = displayTitle;
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/DatasetPage.java]: do you mean to set the displayCitation with a method named setDisplayTitle?

**Comment by ofahimIQSS** [comment]
Very nice, thanks for the fix. Merging
