### PR TITLE
clearAllCachedFormats by DestroyDatasetCommand

### LINKED ISSUE #11470: Deleting a Published Dataset Leaves Orphaned .cached Files in S3
**What steps does it take to reproduce the issue?**

1. Create and publish a dataset containing several files.
2. Delete the dataset from the Dataverse Web UI (destroy a published dataset).
3. Observe the contents of the corresponding S3 bucket path for that dataset.

* When does this issue occur?

After deleting a published dataset using the API.

* Which page(s) does it occur on?

I used the API to delete.

* What happens?

The dataset is removed from Dataverse, but certain `.cached` files (e.g., files created as part of metadata export processes) remain in S3. These orphaned files are not cleaned up, resulting in abandoned storage objects that may persist indefinitely.

* To whom does it occur (all users, curators, superusers)?

Superusers or users with the ability to delete datasets.

* What did you expect to happen?

I expected that deleting a published dataset would remove all associated data, including files in S3 generated by background or export processes (e.g., `.cached` files).

**Which version of Dataverse are you using?**

Observed in Dataverse 6.2.

**Any related open or closed issues to this bug report?**

None found at the time of writing.

**Screenshots:**

Not applicable, though file listings and logs are available on request.

**Are you thinking about creating a pull request for this issue?**

Not at this time. We'd welcome community insight or a fix from core developers.

### PR DESCRIPTION
**Pull request by jo-pol**
**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

- Closes #11470

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DestroyDatasetCommand.java [hunk 1]
```diff
@@ -97,8 +98,16 @@ protected void executeImpl(CommandContext ctxt) throws CommandException {
         // ROLES
         for (DataverseRole ra : ctxt.roles().findByOwnerId(managedDoomed.getId())) {
             ctxt.em().remove(ra);
-        }   
-        
+        }
+
+        ExportService exportService = ExportService.getInstance();
+        try {
+            exportService.clearAllCachedFormats(doomed);
```
Comment (jo-pol) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DestroyDatasetCommand.java]: Note that this removes `export_*.cached` but not the directory/bucket.

**Comment by ofahimIQSS** [comment]
looks good from my end - merging
