### PR TITLE
Harvester improvements.

### LINKED ISSUE #3268: Fix real-time, incremental harvesting from Odum archive
Of the 3000+ datasets harvested from Odum, 50 failed.

For example,
1902.29/10497, grep -c "  Exception processing getRecord()" server.log_2016-08-01T15*

### PR DESCRIPTION
**Pull request by landreev**
fixes the issue with transaction scope when deleting harvested records, per OAI instructions;
plus some cosmetic issues and minor optimizations. (#3268)

## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- closes #3268

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DestroyDatasetCommand.java [hunk 1]
```diff
@@ -92,17 +94,20 @@ protected void executeImpl(CommandContext ctxt) throws CommandException {
...
+            GlobalIdServiceBean idServiceBean = GlobalIdServiceBean.getBean(ctxt);
+            try {
+                if (idServiceBean.alreadyExists(doomed)) {
+                    idServiceBean.deleteIdentifier(doomed);
+                    for (DataFile df : doomed.getFiles()) {
+                        idServiceBean.deleteIdentifier(df);
+                    }
                 }
+            } catch (Exception e) {
+                logger.log(Level.WARNING, "Identifier deletion was not successfull:", e.getMessage());
```
Comment (mheppler) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DestroyDatasetCommand.java]: Typo: "successful"

File: src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java [hunk 2]
```diff
@@ -928,4 +924,35 @@ public long findStorageSize(Dataset dataset, boolean countCachedExtras) throws I
...
+     * 
+     * @param dataset
+     * @param request DataverseRequest (for initializing the DestroyDatasetCommand)
+     * @param hdLogger logger object (in practice, this will be a separate log file created for a specific harvesting job)
+     */
+    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
+    public void deleteHarvestedDataset(Dataset dataset, DataverseRequest request, Logger hdLogger) {
+        // Purge all the SOLR documents associated with this client from the 
+        // index server: 
+        indexService.deleteHarvestedDocuments(dataset);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java]: Should this indexing operation be moved to "on success"?

File: src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java [hunk 3]
```diff
@@ -315,8 +309,7 @@ public void doHarvest(DataverseRequest dataverseRequest, Long harvestingClientId
     
     
     
-    @TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
-    public Long processRecord(DataverseRequest dataverseRequest, Logger hdLogger, PrintWriter importCleanupLog, OaiHandler oaiHandler, String identifier, MutableBoolean recordErrorOccurred, MutableLong processedSizeThisBatch, List<String> deletedIdentifiers) {
+    private Long processRecord(DataverseRequest dataverseRequest, Logger hdLogger, PrintWriter importCleanupLog, OaiHandler oaiHandler, String identifier, MutableBoolean recordErrorOccurred, MutableLong processedSizeThisBatch, List<String> deletedIdentifiers, Date dateStamp) {
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java]: I'm curious why "TransactionAttributeType.NOT_SUPPORTED" has been removed. I'm not saying this is a problem, I'm just a little turned around about why this change is being made.
