### PR TITLE
Iqss/#8380 counter-processor version update

### LINKED ISSUE #6629: Geolite2 database for MDC no longer available at URL /under completely open license
As of Dec 31rst, 2019, it looks like MaxMind, in order to comply with privacy regulations, is adding some conditions to the use of the Geolite2 database used by counter-processor. It is still free, but downloading requires creation of an account at MaxMind and agreeing to a EULA that requires one to keep up to date with the database releases. (The primary concern appears to be that individuals can opt-out under privacy laws and MaxMind needs a way to comply with that for products it has sold (for free). See
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ .

The most basic consequence is that the database is no longer available at the URL specified in http://guides.dataverse.org/en/latest/installation/prerequisites.html and some update is needed.

More broadly, using the database now involves agreeing to update to the latest version within 30 days of being notified. At a minimum the docs should probably note/discuss that as part of the updated download instructions. 

It might also be worthwhile to raise this with the creator of counter-processor / MDC to see if there are ways to simplify/automate and/or whether there are alternatives and whether there are other aspects of counter-processor's functionality that are affected by privacy laws, whether location determination should be an option that can be turned off, etc.

### LINKED ISSUE #8380: Requesting support for a newer version of Counter Processor
Hi
our version of Dataverse is 4.20 .
a few days ago, we decide to use MAKE DATA COUNT for metrics/statistics.
so we download last version of "counter processor" - https://github.com/CDLUC3/counter-processor, via command "git" on Linux Ubuntu.
After Install and configure it, as in documentation of Dataverse. 
After process counter logs, a report json was created.
when we try to upload json on dataverse, we receive this error:
"_curl -X POST "http://localhost:8080/api/admin/makeDataCount/addUsageMetricsFromSushiReport?reportOnDisk=/counter-processor/reports/mdc-report.json"
{"status":"ERROR","code":500,"message":"Internal server error. More details available at the server logs.","incidentId":"a4a2eafa-8a47-490e-84dd-45564acfd388"}_"

file: server.log
_[2022-01-31T11:49:04.060+0000] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler] [tid: _ThreadID=28 _ThreadName=http-listener-1(3)] [timeMillis: 1643629744060] [levelValue: 1000] [[
  API internal error a4a2eafa-8a47-490e-84dd-45564acfd388: Null Pointer
java.lang.NullPointerException
        at edu.harvard.iq.dataverse.makedatacount.DatasetMetricsServiceBean.parseSushiReport(DatasetMetricsServiceBean.java:122)_

link to "DatasetMetricsServiceBean.java" line 122
https://github.com/IQSS/dataverse/blob/v4.20/src/main/java/edu/harvard/iq/dataverse/makedatacount/DatasetMetricsServiceBean.java#L122

seems that Dateverse is not compatible with last version of counter-processor.
the json file created with last verion of counter-processor has "report-datasets" with a hyphen/dash (-)  and the Dataverse code expects report_datasets with an underscore (_). 

after that,
we uninstall this version of counter-processor.
install version that is on documentation of Dataverse.
and we make upload of json to Dataverse with no problems.

_curl -X POST "http://localhost:8080/api/admin/makeDataCount/addUsageMetricsFromSushiReport?reportOnDisk=/usr/local/counter-processor-0.0.1/reports/mdc-report.json"
{"status":"OK","data":{"message":"Usage Metrics Data has been added to all datasets from file  /usr/local/counter-processor-0.0.1/reports/mdc-report.json"}}_

best regard
Agostinho Gomes
Minho University
https://datarepositorium.uminho.pt/

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: This PR updates the parsing of the counter-processor reports in Dataverse to be compatible with the v0.1.04 (latest) version of counter processor and updates the documents to reference that version. It also updates the documentation related to MaxMind's change from making the GeoLite Country database available from a fixed URL to something you have to sign up for and sign an agreement to download. The changes point to MaxMind's documentation about why this was done and how to obtain the database, and notes that this is an optional addition to counter-processor (used to report per country results).

**Which issue(s) this PR closes**:

Closes #8380 
Closes #6629

**Special notes for your reviewer**: The vagrant script references the non-working GeoLite db download URL. I think it is currently failing gracefully but this section could perhaps be removed. Since the new process requires having an account/signing a EULA with MaxMind, probably configuring a cron job to run their update script, etc. I'm not sure it is something we could/should automate. So it may make sense to do something like write a message to say 'follow the guides to install the optional GeoLite Country db for counter-processor to capture per country MakeDataCount statistics.' I'm hoping someone might suggest a change for the script.

**Suggestions on how to test this**: I'll try to test at QDR and report on/fix any issues I find there. For QA testing, configure for Make Data Counts. Update the counter-processor version to v0.1.04 and test that daily results are still being captured. The update should also be backward compatible, i.e. running this PR with counter processor v0.0.1 should also work.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

File: scripts/vagrant/setup-counter-processor.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@ python3.6 -m ensurepip
 COUNTER_USER=counter
```
Comment (pdurbin) [inline scripts/vagrant/setup-counter-processor.sh:11]: Whoops, I missed this when making a review:

> Special notes for your reviewer: The vagrant script references the non-working GeoLite db download URL. I think it is currently failing gracefully but this section could perhaps be removed. Since the new process requires having an account/signing a EULA with MaxMind, probably configuring a cron job to run their update script, etc. I'm not sure it is something we could/should automate. So it may make sense to do something like write a message to say 'follow the guides to install the optional GeoLite Country db for counter-processor to capture per country MakeDataCount statistics.' I'm hoping someone might suggest a change for the script.

I think it would be fine to comment out this part of the Vagrant script. Perhaps with a comment above that section saying "This can no longer be automated. See the Installation Guide."

File: doc/sphinx-guides/source/admin/make-data-count.rst [hunk 2]
```diff
@@ -83,9 +83,9 @@ Configure Counter Processor
```
[the remark this answers is not in the document]
Comment (qqmyers) [reply doc/sphinx-guides/source/admin/make-data-count.rst:83]: FWIW: it is easy to rename the branch but I think that closes the PR (any way around that?) - let me know if this is needed for the QA build.

File: scripts/vagrant/setup-counter-processor.sh (hunk 1 above)
Comment (pdurbin) [reply scripts/vagrant/setup-counter-processor.sh:11]: I see the lines were removed and a note added. Great!

**Review by pdurbin — APPROVED** [review]
I didn't run the code but the changes make sense.

**Comment by qqmyers** [comment]
To make counter-processor 0.1.04 the new default version (e.g. with install instructions for it in the guides, etc.), some additional work is needed on the PR to update the python version (to 3.7+) and update it's install instructions/scripts, etc.

File: doc/sphinx-guides/source/installation/prerequisites.rst [hunk 3]
```diff
@@ -416,43 +416,51 @@ Counter Processor is required to enable Make Data Count metrics in a Dataverse i
...
-        wget https://github.com/CDLUC3/counter-processor/archive/v0.0.1.tar.gz
-        tar xvfz v0.0.1.tar.gz
+        wget https://github.com/CDLUC3/counter-processor/archive/v0.1.04.tar.gz
+        tar xvfz v0.1.04.tar.gz
+        cd /usr/local/counter-processor-0.1.04
+
+Installing GeoLite Country Database
+===================================
+
+Counter Processor can report per country results if the optional GeoLite Country Database is installed. At present, this database is free but to use it one must signing an agreement (EULA) with MaxMind.
```
Comment (pdurbin) [inline doc/sphinx-guides/source/installation/prerequisites.rst:431]:
```suggestion
Counter Processor can report per country results if the optional GeoLite Country Database is installed. At present, this database is free but to use it one must sign an agreement (EULA) with MaxMind.
```
