### PR TITLE
11387 fix input level api

### LINKED ISSUE #11387: Input Level API overwrites existing displayOnCreate settings
**What steps does it take to reproduce the issue?**

1. Set `displayOnCreate` to `true` for a metadata field at input level using the API, e.g., `geographicUnit`.
2. Confirm that the field appears when creating a dataset in the collection (as expected).
3. Use the same API endpoint to update a different field (e.g., `geographicCoverage`) without including the previous field (`geographicUnit`) in the new request.
4. The first field (`geographicUnit`) is no longer shown during dataset creation.

**When does this issue occur?**
When updating input level settings for metadata fields using the API.

**Which page(s) does it occur on?**
During dataset creation, the affected fields are no longer visible.

**What happens?**
Only the fields specified in the last API call retain the `displayOnCreate` configuration. Any fields previously configured are reset unless they are explicitly included in the current request.

**To whom does it occur (all users, curators, superusers)?**
All users creating datasets in the collection.

**What did you expect to happen?**
Expected the API to only update the fields explicitly passed in the request and preserve any previous `displayOnCreate` settings unless overridden.

**Which version of Dataverse are you using?**
v6.6

**Any related open or closed issues to this bug report?**
New feature introduced in https://github.com/IQSS/dataverse/pull/11224 and https://github.com/IQSS/dataverse/pull/11312

**Are you thinking about creating a pull request for this issue?**
Yes, this is something I plan to fix.

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**: fixes input level so that previously entered custom values are not wiped out of the api is used again with other dataset field types being given custom values. the only way to remove a custom value for input levels in a given dataverse is to pass in an empty array for input levels or explicitly re-setting them via the api with a json array that has the default values.

**Which issue(s) this PR closes**:

- Closes #11387 

**Special notes for your reviewer**:
When running the integration tests (DataversesIT#testUpdateInputLevels)  I noticed an error in the log saying that the command was receiving an empty or null input level array. This error was also present in the previous version of the test and doesn't prevent them from passing.
dev_dataverse>   Error while executing command edu.harvard.iq.dataverse.engine.command.impl.UpdateDataverseInputLevelsCommand@14fb88b8
dev_dataverse> edu.harvard.iq.dataverse.engine.command.exception.CommandException: Error while updating dataverse input levels: Input level list cannot be null or empty
dev_dataverse> 	at edu.harvard.iq.dataverse.engine.command.impl.UpdateDataverseInputLevelsCommand.execute(UpdateDataverseInputLevelsCommand.java:30)
dev_dataverse> 	at edu.harvard.iq.dataverse.engine.command.impl.UpdateDataverseInputLevelsCommand.execute(UpdateDataverseInputLevelsCommand.java:16)
**Suggestions on how to test this**:
Run the input level update api several times and make sure that previous values are not deleted unless explicitly included in the api (or an empty array is passed)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
no
**Is there a release notes update needed for this change?**:
no
**Additional documentation**:
none

### CODE REVIEW

File: src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java [hunk 1]
```diff
@@ -1255,6 +1255,81 @@ public void testUpdateInputLevels() {
...
+        testInputLevelNames = new String[]{"subtitle", "otherReferences"};
+        testRequiredInputLevels = new boolean[] {false, false};
+        testIncludedInputLevels = new boolean[] {true, true};
+        testDisplayOnCreate = new boolean[] {false, true};
+        
+        updateDataverseInputLevelsResponse = UtilIT.updateDataverseInputLevels(dataverseAlias, testInputLevelNames, testRequiredInputLevels, testIncludedInputLevels, testDisplayOnCreate, apiToken);
+        updateDataverseInputLevelsResponse.prettyPrint();
+        
+        subtitleInputLevelIndex = 0;
+        int otherReferencesInputLevelIndex = 0;
```
Comment (stevenwinship) [inline src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java]: otherReferencesInputLevelIndex is not used in the test and can either be checked or removed

File: src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java [hunk 2]
```diff
@@ -1255,6 +1255,81 @@ public void testUpdateInputLevels() {
...
+        
+        //Add new types and see that previously changed ones remain as before... #11387
+        testInputLevelNames = new String[]{"subtitle", "relatedMaterial"};
+       
+        testRequiredInputLevels = new boolean[] {false, false};
+        testIncludedInputLevels = new boolean[] {true, true};
+        boolean [] testDisplayOnCreate = new boolean[] {true, false};
+         updateDataverseInputLevelsResponse = UtilIT.updateDataverseInputLevels(dataverseAlias, testInputLevelNames, testRequiredInputLevels, testIncludedInputLevels, testDisplayOnCreate, apiToken);
+         updateDataverseInputLevelsResponse.prettyPrint();
+         int subtitleInputLevelIndex = 0;
```
Comment (stevenwinship) [inline src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java]: setting the index to 0 can lead to a bad check if the names "subtitle" or "relatedMaterial" aren't found. They will be assumed to be index 0. Maybe set them to -1 and assert that they are > -1

File: src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java [hunk 3]
```diff
@@ -1255,6 +1255,81 @@ public void testUpdateInputLevels() {
...
+ 
+        testInputLevelNames = new String[]{"subtitle", "otherReferences"};
+        testRequiredInputLevels = new boolean[] {false, false};
+        testIncludedInputLevels = new boolean[] {true, true};
+        testDisplayOnCreate = new boolean[] {false, true};
+        
+        updateDataverseInputLevelsResponse = UtilIT.updateDataverseInputLevels(dataverseAlias, testInputLevelNames, testRequiredInputLevels, testIncludedInputLevels, testDisplayOnCreate, apiToken);
+        updateDataverseInputLevelsResponse.prettyPrint();
+        
+        subtitleInputLevelIndex = 0;
```
Comment (stevenwinship) [inline src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java:1306]: Same issue as above. init to -1

File: src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java [hunk 4]
```diff
@@ -307,7 +307,7 @@ public void testCustomOptions() throws CommandException {
             i++;
         }
         
-        assertTrue( dftilsDeleted );
+       // assertTrue( dftilsDeleted ); we no longer delete when adding new input levels to preserve previously created
```
Comment (stevenwinship) [inline src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java:310]: This seems to contradict the api docs. Please add a release note and modify the doc

Update Collection Input Levels
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Updates the dataset field type input levels in a collection.

Please note that this endpoint overwrites all the input levels of the collection page, so if you want to keep the existing ones, you will need to add them to the JSON request body.

File: src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java (hunk 1 above)
Comment (sekmiller) [reply src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java]: OK. will do.

File: src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java (hunk 4 above)
Comment (sekmiller) [reply src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java:310]: Good catch. This was reported as a bug, not a feature/change request.

Comment (sekmiller) [reply src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java:310]: I added a release note and modified the doc, but I will bring it up in Stand Up to make sure we really want to do this

File: doc/release-notes/11387-modify-input-level-api.md [hunk 5]
```diff
@@ -0,0 +1,3 @@
+### Update Collection Input Level API Changed
+
+- This endpoint will no longer delete the custom input levels previously modified for the given collection. In order to update a previously modified custom input level, it must be included in the JSON provided to the api.
```
Comment (pdurbin) [inline doc/release-notes/11387-modify-input-level-api.md:3]: Can you please add this to api/changelog.rst?

Comment (sekmiller) [reply doc/release-notes/11387-modify-input-level-api.md:3]: OK. Done

File: src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java (hunk 4 above)
Comment (stevenwinship) [reply src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java:310]: What is the outcome of wanting to do this? Should I continue to review this?

File: src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java (hunk 3 above)
Comment (stevenwinship) [reply src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java:1306]: Still not addressed

Comment (stevenwinship) [reply src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java:1306]: Not a big deal. Will approve without this change

**Review by stevenwinship — APPROVED** [review]

**Comment by stevenwinship** [comment]
Old levels are deleted by sending an empty list (delete all) then sending the new/modified list

Updating the doc to note this

**Comment by ofahimIQSS** [comment]
looks like continuous integration is failing on this one

**Comment by sekmiller** [comment]
All checks passing now

**Comment by ofahimIQSS** [comment]
very nice - tests passing - merging
