### PR TITLE
fix: issues in exporters and citations for PermaLink/non-DOI PIDs

### LINKED ISSUE #10768: Suggestion: Permalinks in metadata exporters
**Overview of the Suggestion/What inspired this idea?**

Looking at the metadata export for datasets with permalink PIDs, I found that the treatment of permalinks is currently inconsistent. Some export formats use the permalink itself as the dataset identifier + within the citation string, others use a link of the format `$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK`.

Here are relevant snippets from each export format:

DataCite:

```
    <identifier identifierType="DOI">$PERMALINK</identifier>
```

(wrong identifierType is already being discussed here: #10759)

OpenAire:

```
<identifier>$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK</identifier>
```

Schema.org:

```
"@id":"$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK",
"identifier":"$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK"
```

DDI:

```
<IDNo agency="perma">perma:$PERMALINK</IDNo>
...
<biblCit>$AUTHORS, $YEARS, "$TITLE", $DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK, Root, V1</biblCit>
...
<holdings URI="$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK"/>
```

DDI HTML codebook: same as DDI

Dublin Core:

```
<dcterms:identifier>$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK</dcterms:identifier>
```

JSON:

```
"persistentUrl":"$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK"
...
"datasetPersistentId":"perma:$PERMALINK"
...
"citation":"$AUTHORS, $YEAR, \"$TITLE\", $DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK, Root, V1"
```

OAI_ORE:

```
"@id": "$DATAVERSE_HOST/api/datasets/export?exporter=OAI_ORE&persistentId=$DATAVERSE_HOST/citation?persistentId=perma:$PERMALINK",
...
"ore:describes": {
  "@id": "http://localhost:8080/citation?persistentId=perma:https://clinicaltrials.gov/study/NCT00080262",
  ...
}
```

**What existing behavior do you want changed?**

We would like to suggest that

1. the treatment of Permalink PIDs in all exporters should be consistent
2. preferably the persistent identifier of the dataset should be simply the Permalink, as in the Datacite export or in the JSON export

**Any brand new behavior do you want to add to Dataverse?**
 
none

**Any open or closed issues related to this suggestion?**

maybe #10615 (refactoring of Datacite export code), not aware of any others

**Are you thinking about creating a pull request for this issue?**

yes, we would be interested in creating a PR :)

cc @johannes-darms

### LINKED ISSUE #10769: Bug: BibTeX + EndNote XML citation output for dataset with Permalink
**What steps does it take to reproduce the issue?**

1. Create dataset with permalink PID (in my example, the permalink of my dataset is `https://clinicaltrials.gov/study/NCT00080262`)
2. Open dataset page and click "Cite Dataset" > "BibTeX" or "EndNote XML"

Two problems:

1. I'm seeing weird output in the BibTeX output in L1 and line `doi` (missing `http` and extra slash after `http`).

   In the EndNote XML output, there is also an extra slash in `<electronic-resource-num>`.

    I briefly checked the code ([BibTeX](https://github.com/IQSS/dataverse/blob/b67d732921a3e84d4450a5ee18790aeab07afaed/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L254), [EndNote XML](https://github.com/IQSS/dataverse/blob/b67d732921a3e84d4450a5ee18790aeab07afaed/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L440)) and I'm not sure why?

   The RIS citation is fine.
4. in the BibTeX output, the permalink should not be given as `doi` since it's not a DOI

BibTeX:

```
@data{s://clinicaltrials.gov/study/NCT00080262_2024,
author = {$AUTHORS},
publisher = {Root},
title = {{$TITLE}},
year = {2024},
version = {V1},
doi = {http/s://clinicaltrials.gov/study/NCT00080262},
url = {http://localhost:8080/citation?persistentId=perma:https://clinicaltrials.gov/study/NCT00080262}
}
```

EndNote XML:

`<?xml version='1.0' encoding='UTF-8'?><xml><records><record><ref-type name="Dataset">59</ref-type><contributors><authors>...</authors></contributors><titles><title>...</title></titles><section>...</section><dates><year>...</year></dates><edition>...</edition><publisher>...</publisher><urls><related-urls><url>http://localhost:8080/citation?persistentId=perma:https://clinicaltrials.gov/study/NCT00080262</url></related-urls></urls><electronic-resource-num>perma/http/s://clinicaltrials.gov/study/NCT00080262</electronic-resource-num></record></records></xml>`

**Which version of Dataverse are you using?**

6.2

**Any related open or closed issues to this bug report?**

not aware

**Screenshots:**

\-

**Are you thinking about creating a pull request for this issue?**

yes, would be interested

### LINKED ISSUE #11165: Permalink PIDs: UnmanagedPermaLinkProvider is not configured
I am having some trouble setting up a Permalink pid provider on a newly installed Dataverse 6.5. When creating a new dataset using this pid provider, I am redirected to the draft dataset page, but Dataverse cannot find said page. Internally, Dataverse raises the following error
```
CommandException, when attempting to update the dataset: PID Provider UnmanagedPermaLinkProvider is not configured.
```
and no dataset is created. No new entries show up in the `dataset` table in the psql database.

### Setup
I installed Dataverse using the [Ansible Playbook](https://github.com/gdcc/dataverse-ansible) — which configures a FAKE doi provider — and then manually configured an additional perma pid provider as follows:

```
# Default set during installation
-Ddataverse.pid.fake.type=FAKE
-Ddataverse.pid.fake.label=Fake DOI Provider
-Ddataverse.pid.fake.authority=10.5072
-Ddataverse.pid.fake.shoulder=FK2/

# My permalink provider
-Ddataverse.pid.perma1.type=perma
-Ddataverse.pid.perma1.label=PermaLink
-Ddataverse.pid.perma1.authority=abc1234
-Ddataverse.pid.perma1.permalink.separator=-
-Ddataverse.pid.perma1.shoulder=ds-
-Ddataverse.pid.perma1.permalink.identifier-generation-style=randomString
-Ddataverse.pid.perma1.permalink.base-url=https://dataverse.abc1234.uni-due.de/

# I overwrote these settings to make perma1 the default provider, but to offer both.
-Ddataverse.pid.providers=fake,perma1
-Ddataverse.pid.default-provider=perma1
```

Then I removed all PID-related settings via the `/api/admin/settings` API and restarted payara. Both providers show up in the user interface. Using the FAKE provider works, but when I switch to the perma provider I get the following error in `server.log`:

```
CommandException, when attempting to update the dataset: PID Provider UnmanagedPermaLinkProvider is not configured.
edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: PID Provider UnmanagedPermaLinkProvider is not configured.
        at edu.harvard.iq.dataverse.engine.command.impl.CreateNewDatasetCommand.handlePid(CreateNewDatasetCommand.java:100)
        at edu.harvard.iq.dataverse.engine.command.impl.AbstractCreateDatasetCommand.execute(AbstractCreateDatasetCommand.java:134)
        at edu.harvard.iq.dataverse.engine.command.impl.AbstractCreateDatasetCommand.execute(AbstractCreateDatasetCommand.java:26)
        at edu.harvard.iq.dataverse.EjbDataverseEngineInner.submit(EjbDataverseEngineInner.java:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
[...] 
```

### Other approaches

I also tried a setup with only the permalink provider (without the fake doi provider). That setup had the same problem.

On an existing Dataverse 6.2 server, we have the following setup which works as expected:
```
-Ddataverse.pid.perma1.authority=foo
-Ddataverse.pid.perma1.permalink.separator=/
-Ddataverse.pid.perma1.shoulder=ds-
```

## Mitigation

As suggested by Jim, I modified the shoulder and separator. I could not find a value for the shoulder that worked, but removing the shoulder altogether got the system running! I tried the following:

- `"ds-"` with separator `"/"`: Yields the same error
- `"ds/"` with separator `"/"`: Yields the same error
- `"ds"` with separator `"/"`: Yields the same error
-  No shoulder set with separator `"/"`: Works!

## Which version of Dataverse are you using?

- Dataverse 6.5 
- Payara 6.2023.9

## Any related open or closed issues to this bug report?

We faced problems with separators in permalink PIDs before. I am not sure if this is related, but just to be sure: #10564

This issue was also discussed in [this zulip thread](https://dataverse.zulipchat.com/#narrow/channel/378866-troubleshooting/topic/Permalink.20PIDs.3A.20UnmanagedPermaLinkProvider.20is.20not.20configured) and on the [mailing list](https://groups.google.com/g/dataverse-community/c/1Ec6iT5OKio/m/MbcKyHbuCgAJ).

### PR DESCRIPTION
**Pull request by vera**
**What this PR does / why we need it**:

This PR fixes three issues with PermaLink PIDs in metadata exporters and citations.

1. DDI & DDI HTML exporters: Previously, the export included `<IDNo agency="perma">perma:N4H-/M015D56B</IDNo>` (DDI XML) and "Identification Number: perma:N4H-/M015D56B" (DDI HTML). This change removes the extra slash in the middle of the identifier.

2. EndNote XML citation: Previously, the citation included `<electronic-resource-num>perma/N4H-/M015D56B</electronic-resource-num>`. With this change, `perma/` is replaced with `perma:` and the extra slash in the middle of the identifier is also removed. (Note, this is the only change that also affects DOIs: for DOIs, `doi/` is replaced with `doi:`.)

3. BibTeX citation: Previously, `doi = {...}` was always included in the citation. With this change, it is only included when the PID is actually a DOI. A `url = {...}` is always included (this was already the case).

**Which issue(s) this PR closes**:

In combination with #10775 and #10759 (or #10615), this addresses #10769 and #10768

- Closes #10769
- Closes #10768
- Closes #11165

**Special notes for your reviewer**:

\-

**Suggestions on how to test this**:
(from @qqmyers)
1) Configure permalink PID providers w/  "" and "/" separators, create datasets using them and verify that the DDI/DDI Html exports do not/do contain the / separator (respectively). Confirm that  a Fake DOI provider (or test DataCite provider) still work as before w.r.t. how they appear in the DDI/DDI Html exports.

2) Verify that the EndNote citation for datasets using DOIs and PermaLinks include the PIDs as specified in the best option as discussed in [this comment](https://github.com/IQSS/dataverse/pull/10790#issuecomment-2433406188) and below. Handles could also be tested but I'm not sure if there's a test setup for that.

3) Verify that the BibTeX citation format uses `doi=` for DOIs and only `url=` for PermaLinks/Handles (if we can test them). (pre-PR PermaLinks would have an extra `doi=` line.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

\-

**Is there a release notes update needed for this change?**:
Provided

**Additional documentation**:

\-

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java [hunk 1]
```diff
@@ -163,7 +163,7 @@ private static void createStdyDscr(XMLStreamWriter xmlw, DatasetDTO datasetDto)
         String persistentAuthority = datasetDto.getAuthority();
         String persistentId = datasetDto.getIdentifier();
 
-        String pid = persistentProtocol + ":" + persistentAuthority + "/" + persistentId;
+        String pid = persistentProtocol + ":" + persistentAuthority + ("perma".equals(persistentAgency) ? "" : "/") + persistentId;
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:166]: permalinks can have a separator - seems like we need to add that to the DTO?

File: src/main/java/edu/harvard/iq/dataverse/DataCitation.java [hunk 2]
```diff
@@ -619,8 +621,7 @@ private void createEndNoteXML(XMLStreamWriter xmlw) throws XMLStreamException {
         }
         if (persistentId != null) {
             xmlw.writeStartElement("electronic-resource-num");
-            String electResourceNum = persistentId.getProtocol() + "/" + persistentId.getAuthority() + "/"
-                    + persistentId.getIdentifier();
+            String electResourceNum = persistentId.asString();
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/DataCitation.java:624]: Has it been verified that an initial : after protocol is OK for EndNote import? It seems like the original code used / because ICPSR did. Can someone look at what EndNote exports and make sure we match it here? @adam3smith says he can check this next week if no one else has access.

File: src/test/java/edu/harvard/iq/dataverse/DataCitationTest.java [hunk 3]
```diff
@@ -266,7 +266,7 @@ public void testToEndNoteString_withTitleAndAuthor() throws ParseException {
             "<edition>V1</edition>" +
             "<publisher>LibraScholar</publisher>" +
             "<urls><related-urls><url>https://doi.org/10.5072/FK2/LK0D1H</url></related-urls></urls>" +
-            "<electronic-resource-num>doi/10.5072/FK2/LK0D1H</electronic-resource-num>" +
+            "<electronic-resource-num>doi:10.5072/FK2/LK0D1H</electronic-resource-num>" +
```
Comment (pdurbin) [inline src/test/java/edu/harvard/iq/dataverse/DataCitationTest.java:269]: It's weird that this old test expected `doi/10...` instead of `doi:10...`. It feels like this PR is cleaning things up! ❤️

File: src/main/java/edu/harvard/iq/dataverse/DataCitation.java (hunk 2 above)
Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/DataCitation.java:624]: I see, I wondered about that slash there. I tried to find some info on the EndNote XML format but found only [this schema](https://support.clarivate.com/Endnote/s/article/EndNote-XML-Document-Type-Definition?language=en_US), which didn't specify anything about the format of `electronic-resource-num`, so I thought it might have been a mistake to use the slash here. It would be great if someone could check.

File: src/test/java/edu/harvard/iq/dataverse/DataCitationTest.java (hunk 3 above)
Comment (vera) [reply src/test/java/edu/harvard/iq/dataverse/DataCitationTest.java:269]: @qqmyers commented above that this slash might be required by EndNote, although it does look weird to me :thinking:

File: src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java (hunk 1 above)
Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:166]: shoulder just becomes part of the identifier

Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:166]: Ah I see

Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: I've just pushed a commit adding the separator to the DTO. It's marked as WIP because for some reason it doesn't work yet (separator is always `null`). I will have time to troubleshoot tomorrow

If I am on the wrong track with that commit, please let me know!

Comment (johannes-darms) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: Do we really need to change the domain object? Can't we delegate the PID string generation to `GlobalId#toString()`?

Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: > I've just pushed a commit adding the separator to the DTO. It's marked as WIP because for some reason it doesn't work yet (separator is always `null`). I will have time to troubleshoot tomorrow

This issue is now fixed. Tested with DOI, PermaLink without separator and PermaLink with separator

Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: > Can't we delegate the PID string generation to GlobalId#toString()?

@qqmyers would you prefer a solution using the GlobalId method instead of adding the separator to the database? I could take a look at implementing it that way instead (later today or on Monday)

Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: At first I was thinking that you didn't need the new column on dvobject (you can use PidUtil.parseAsGlobalID(String protocol, String authority, String identifier) to get a GlobalId), but it actually solves a limitation of permalinks right now - you can't have two providers that differ only by the separator because we don't store the separator and have to infer it. With that in mind, I think the new column is a good way to go. (I'd still use the GlobalId convenience methods whenever they're available, to avoid replicating the formatting code - looked like you mostly do that now except in DDIExportUtil where there's weirdness from tests sending null identifiers and for the one format with { in it.)

File: src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java [hunk 4]
```diff
@@ -162,11 +162,12 @@ private static void createStdyDscr(XMLStreamWriter xmlw, DatasetDTO datasetDto)
...
         String persistentId = datasetDto.getIdentifier();
+        String persistentSeparator = datasetDto.getSeparator();
 
-        String pid = persistentProtocol + ":" + persistentAuthority + "/" + persistentId;
+        String pid = persistentProtocol + ":" + persistentAuthority + persistentSeparator + persistentId;
         String pidUri = pid;
         //Some tests don't send real PIDs - don't try to get their URL form
-        if(!pidUri.equals("null:null/null")) {
+        if(!pidUri.equals("null:nullnullnull")) {
             pidUri= PidUtil.parseAsGlobalID(persistentProtocol, persistentAuthority, persistentId).asURL();
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:171]: Can you avoid line 167 by checking for parseAsGlobalId returning null here and setting pid/pidUri using GlobalId if it exists and to the constant "null:nullnullnull" if it doesn't? (Mostly a minor style thing but it avoids writing out unexpected invalid identifier entries as well.)

File: src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java [hunk 5]
```diff
@@ -337,14 +338,15 @@ private static void writeDocDescElement (XMLStreamWriter xmlw, DatasetDTO datase
...
+        String persistentSeparator = datasetDto.getSeparator();
         
         xmlw.writeStartElement("docDscr");
         xmlw.writeStartElement("citation");
         xmlw.writeStartElement("titlStmt");
         writeFullElement(xmlw, "titl", dto2Primitive(version, DatasetFieldConstant.title), datasetDto.getMetadataLanguage());
         xmlw.writeStartElement("IDNo");
         writeAttribute(xmlw, "agency", persistentAgency);
-        xmlw.writeCharacters(persistentProtocol + ":" + persistentAuthority + "/" + persistentId);
+        xmlw.writeCharacters(persistentProtocol + ":" + persistentAuthority + persistentSeparator + persistentId);
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:349]: same - can you parse the authority/separator/identifier and use GlobalId.asString() ?

File: src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java (hunk 4 above)
Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: Done!

File: src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java (hunk 5 above)
Comment (vera) [reply src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java]: done!

**Comment by vera** [comment]
Hm. I tested this with DOIs, PermaLinks without separators and PermaLinks with separators and the export looks fine. However, I just saw that when I create a new dataset with a PermaLink with a separator, it doesn't actually get stored in the db (`separator` is `null`).

I think a `setSeparator` call needs to be added here in `AbstractPidProvider#generatePid`?

https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/pidproviders/AbstractPidProvider.java#L183

I also briefly tried adding unit tests for the export of PermaLink datasets to `DdiExportUtilTest`, but I didn't find an easy way to configure a PermaLink provider, is there one?

**Comment by qqmyers** [comment]
You probably need to set the separator to / in the Abstract class and to the real one in the Perma provider. 

There are some unit tests for the providers - see the PidUtilTest class and I think you can set up whatever provider you want that way.

**Comment by vera** [comment]
Thanks, fixed the bug and added two tests. Now I think the only open issue is the question about the format of the EndNote citation

**Comment by qqmyers** [comment]
@vera we're trying to move this forward through review/QA. Can you update from develop and fix the merge issues? I'm checking on the question about EndNote again.

**Comment by vera** [comment]
@qqmyers that's great, thank you. I've resolved the merge issues.

**Comment by qqmyers** [comment]
Thanks @vera - now it looks like there are DdiExportUtilTest failures. The results are missing `/citation?persistentId=perma:`

**Comment by vera** [comment]
Yep should be fixed :)

**Comment by adam3smith** [comment]
Jim asked me to look at the Endnote XML export change: this doesn't cause new issues, but `doi:` isn't ideal either.
Both Endnote and Zotero will import the string in `<electronic-resource-num>` as is to the DOI field. That means both doi:10.1234/5678 and doi/10.1234/5678 produce incorrect citations unless fixed. 
Here are some suggestion for better handling this:

**Best option:** Completely separate the handling of DOI and handle on export:
DOI goes into `<electronic-resource-num>` without any prefix
handle goes into `<urls><web-urls><url>`

**Second best option:** Parse the perma prefix separately: 
DOI goes into `<electronic-resource-num>` without any prefix
handle goes into `<electronic-resource-num>` with either hdl/ or the full handle URL prefix

**Third best option**: Put all identifiers into `<electronic-resource-num>` without prefix (will get handles wrong, but they can be detected otherwise.

I think the behavior in this PR is fourth best if the goal of metadata export is to get metadata into reference managers and citations so they produce correct&accurate references

**Comment by vera** [comment]
Thanks for checking! 

Should I go ahead and implement one of those options? (the best option?)

**Comment by qqmyers** [comment]
Given that the EndNote format now changes, I'd suggest adding a short release note pointing out this improvement/backward incompatibility.

**Comment by vera** [comment]
@adam3smith Currently, all PID URLs (https://doi.org/..., https://hdl.handle.net/... or the permalink) are already inserted under `<urls><related-urls><url>`:

https://github.com/IQSS/dataverse/blob/07e327ca6daa35a83cbb8eb2a9f7b8e040ce9cb2/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L599-L605

Would you recommend changing that to `<urls><web-urls><url>` in general?

**Comment by vera** [comment]
I've now implemented the best option as suggested:

* removing prefix from `electronic-resource-num`
* inserting handles and PermaLinks as `web-urls`
* inserting DOIs as `related-urls` (no change to current behavior)

If DOIs should also be inserted as `web-urls`, we could also do that.

(FYI, I am out of office next week. :))

**Comment by qqmyers** [comment]
Thanks @vera - can you add a quick release note?

**Review by qqmyers — APPROVED** [review]
Looks good. I added a release note. Thanks for the extra work with the EndNote format!

**Comment by vera** [comment]
Thanks for adding the release note! @qqmyers

**Comment by qqmyers** [comment]
@vera - can you update this to fix the conflicts? Also - I'm going to create a PR today against your branch to add a test to make sure Perma PID generation with a separator works (see #11165). If you merge that, the test will get merged along with your PR once it goes through QA.

**Comment by qqmyers** [comment]
I created https://github.com/vera/dataverse/pull/2 with the new test.

**Comment by vera** [comment]
@qqmyers done :+1:

**Comment by ofahimIQSS** [comment]
Hello! Can we please resolve the branch conflicts on this PR. Thank you!

**Comment by vera** [comment]
@ofahimIQSS done!

**Comment by ofahimIQSS** [comment]
Fixes have been validated, regression testing in progress. I will merge the PR once I'm done. Here are some screenshots below:
[testing 10790.docx](https://github.com/user-attachments/files/18694390/testing.10790.docx)

**Comment by ofahimIQSS** [comment]
No issues found during my regression testing - merging PR
