### PR TITLE
fix search files to return latest published citation

### LINKED ISSUE #10735: Search API: File dataset_name and dataset_citation refer to different versions
**What steps does it take to reproduce the issue?**

1. Create a dataset with a file
2. Publish the dataset
3. Edit the title of the dataset
4. use the search API to get the file, for example, http://localhost:8000/api/v1/search?q=*&type=file&sort=date&order=desc&per_page=10&start=0&subtree=root
5. The title in the dataset_name field doesn't match the title in the dataset_citation (see screenshot)

* When does this issue occur?
When dataset metadata is edited, but not file metadata

* Which page(s) does it occurs on?
N/A

* What happens?

* To whom does it occur (all users, curators, superusers)?
All

* What did you expect to happen?
The dataset_citation field should be for the released version of the file, not the draft version

**Which version of Dataverse are you using?**
6.2

**Any related open or closed issues to this bug report?**

**Screenshots:**

Screenshot 2024-07-31 at 1 28 41 PM

### PR DESCRIPTION
**Pull request by stevenwinship**
**What this PR does / why we need it**: Search should not return DRAFT information when a dataset is updated after publishing

**Which issue(s) this PR closes**:https://github.com/IQSS/dataverse/issues/10735

- Closes #10735

**Special notes for your reviewer**:

**Suggestions on how to test this**: Follow the steps listed in the issue.
open in browser: http://localhost:8080/api/v1/search?q=*&type=file&sort=date&order=desc&per_page=10&start=0&subtree=root

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: No

**Is there a release notes update needed for this change?**: Included

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java [hunk 1]
```diff
@@ -1328,7 +1328,8 @@ public SolrInputDocuments toSolrDocs(IndexableDataset indexableDataset, Set<Long
             }
             LocalDate embargoEndDate=null;
             LocalDate retentionEndDate=null;
-            final String datasetCitation = dataset.getCitation();
+            final String datasetCitation = (dataset.isReleased() && dataset.getReleasedVersion() != null) ?
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java:1331]: You wouldn't ever expect that a released dataset wouldn't have a released version unless maybe there's a deaccessioned version, maybe?

**Review by sekmiller — APPROVED** [review]
Looks good. Is it worth fixing that documentation anomaly you noticed where we show a search result that illustrates the bug? Also probably need to update from dev and this will go in after 6.5 is releaesd

**Comment by ofahimIQSS** [comment]
Can we please update the <revision>6.4</revision> to 6.5 in the dataverse/modules/dataverse-parent
/pom.xml

**Comment by ofahimIQSS** [comment]
Can we please update the <revision>6.4</revision> to 6.5 in the dataverse/modules/dataverse-parent
/pom.xml

**Comment by ofahimIQSS** [comment]
Fix looks good

https://github.com/user-attachments/assets/eeb3b925-37e9-4bd8-96df-3d6af49870ba
