### PR TITLE
6641 search ui bug

### LINKED ISSUE #6641: Search - UI bug: Strange dataverse ID and duplicate selected facets displaying above results table
**What's wrong?:**

Strange selected facets are displayed above the results table on the dataverse pg, when using the filter facet links in the side bar.

**Use Case:**

When on a sub-dataverse (not root), then filtering for just files, and then selecting any additional facet, you end up with some strange dataverse ID (`subTreePaths: /####)`) and dataverse/dataset/file types (`Type: (files)`) displayed above the results table. Additionally, you get duplicate `Type: (files)` selections when you deselect the additional facets.

Screen Shot 2020-02-12 at 9 59 11 AM

**How to fix?**

Obviously we do not want to display the strange ID facet, but also I believe that displaying the `Type: (files)` is a bug, as it does not display until I have made an additional facet selection. If I only click the Files facets label, there is no selected facet displayed.

For example, the only selected facets displayed for this search URL (https://dataverse.harvard.edu/dataverse/the_review?q=&fq2=publicationDate%3A%222019%22&fq0=subtreePaths%3A%22%2F2867131%22&fq1=dvObjectType%3A%28datasets%29&types=datasets&sort=dateSort&order=) should be `Publication Year: 2019`.

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**:
This PR prevents the display of duplicate filter query facets on the Dataverse Page. It also removes the subtree and dvobject type facets from the selected filter queries display.

**Which issue(s) this PR closes**:

Closes #6641 Search UI Bug

**Special notes for your reviewer**:

**Suggestions on how to test this**:
From a sub-dataverse select multiple facets and verify that search works as expected.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Bug fix

**Is there a release notes update needed for this change?**:
No
**Additional documentation**:
None

### CODE REVIEW

**Comment by pdurbin** [comment]
I'm a little confused about the fix. I thought we wanted to go back to how things were. If I look at ADA running 4.6.1 for example (screenshot below), we only see "Publication Date" and nothing about `subtreePaths` or `Type`. Sort of a clean look, in my opinion.

## 4.6.1

Screen Shot 2020-08-04 at 10 33 59 AM

## This pull request

Screen Shot 2020-08-04 at 10 33 53 AM

**Comment by mheppler** [comment]
@sekmiller, the suggestion from @pdurbin above is correct. The intention of opening the issue and reporting the bug was to return those selected facet components to their original functionality, as outlined in the 4.6.1 screenshot.

File: src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 1]
```diff
@@ -291,6 +294,7 @@ public void search(boolean onlyDataRelatedToMe) {
                 /**
                  * @todo centralize this into SearchServiceBean
                  */
+                if (!isfilterQueryAlreadyInMap(filterDownToSubtree))
                 filterQueriesFinal.add(filterDownToSubtree);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:298]: The lack of curly braces (preferred) or indentation of the code in the "if" is confusing.

File: src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 2]
```diff
@@ -475,12 +481,11 @@ public void search(boolean onlyDataRelatedToMe) {
...
                 }
             }
-            
-
-            
+                        
             dataversePage.setQuery(query);
             dataversePage.setFacetCategoryList(facetCategoryList);
-            dataversePage.setFilterQueries(filterQueriesFinal);
+            dataversePage.setFilterQueries(filterQueriesDisplay);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:487]: Is this setFilterQueries the crux of the bug? Of #6641? I see some conversation at https://github.com/IQSS/dataverse/pull/6473/commits/cbad0273542534fb41f083143d9016be7843a6cc#r360054910 about it was switched from `filterQueries` to `filterQueriesFinal` in cbad027 (part of pull request #6473). I guess I'm wondering if a one line change to switch it back from `filterQueriesFinal` to `filterQueries` would fix it the bug.

Screen Shot 2020-08-04 at 12 21 56 PM

Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:487]: A one line fix, of course would be nice (and preferred) though we should make sure we understand why that line was changed in the first place. @sekmiller can you look at this and try to understand? Maybe build a branch with the one line change to see if it fixes it, then we can decide if how to get both issues to work?

Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: More than a one line fix but fairly simple. The addition of the DVobject types and subtree to the list of filter queries was necessary for the fix in #6268. I added a method to the SearchIncludeFragment getTypeFromFilterQuery in order to not render those filter queries in the search-include-fragment (see lines 341-342)

File: src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java (hunk 1 above)
Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: re-did curly braces here.

Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: I no longer see the confusing "if". Thanks.

File: src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java (hunk 2 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: I see. I kept wondering why we're adding more code in this pull request when I thought we'd be reverting something. Because the new types were added recently (DvObject and subtree), now we need to hide them, it sounds like.

Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: Right and also during development I noticed that the filter queries were being added multiple times hence the isFilterQueryAlreadyInMap method.
