### PR TITLE
Single retry when datafile checksum validation fails

### LINKED ISSUE #10114: Publish fails for large datasets on some s3 implementations
**What steps does it take to reproduce the issue?**
When using s3 as storage, publish a large dataset where checksum verification takes longer than 30 minutes.

* When does this issue occur?
When publishing datasets with many large files where checksum validation takes longer than 30 minutes. This happens consistently on our installation with OpenStack s3 implementation.

* Which page(s) does it occurs on?
Dataset publish.

* What happens?
S3 closes the connection unexpectedly.

```
java.lang.RuntimeException: java.net.SocketException: Connection reset by peer (Write failed)
  at edu.harvard.iq.dataverse.util.FileUtil.calculateChecksum(FileUtil.java:742)
  at edu.harvard.iq.dataverse.util.FileUtil.validateDataFileChecksum(FileUtil.java:1902)
  at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.validateDataFiles(FinalizeDatasetPublicationCommand.java:325)
  at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:89)
  at edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand.execute(FinalizeDatasetPublicationCommand.java:50)
  at edu.harvard.iq.dataverse.EjbDataverseEngineInner.submit(EjbDataverseEngineInner.java:36)
```

* To whom does it occur (all users, curators, superusers)?
Users with publish permissions.

* What did you expect to happen?
Dataset gets published.

**Which version of Dataverse are you using?**
5.14, 6.0, current develop branch, ...

**Any related open or closed issues to this bug report?**
No.

**Screenshots:**

image

### PR DESCRIPTION
**Pull request by ErykKul**
**What this PR does / why we need it**:
It fixes the problem when publishing large datasets, and the s3 server closes the connection. On some installations, this happens every 20 to 30 minutes. In that case, publishing of large datasets is not possible without disabling the validation.

**Which issue(s) this PR closes**:

Closes #10114 

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No

**Is there a release notes update needed for this change?**:
No

**Additional documentation**:
The fix implements a single retry when datafile validation fails. If the fail was due to a lost connection, the checksum gets recomputed and the publishing succeeds.

### CODE REVIEW

**Comment by ErykKul** [comment]
Link to the conversation on the Google Groups:
https://groups.google.com/g/dataverse-community/c/cQ3k8OvhHcI/m/vhDreGXTAAAJ

File: src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java [hunk 1]
```diff
@@ -1449,6 +1449,16 @@ public static S3AccessIO getS3AccessForDirectUpload(Dataset dataset) {
     	return s3io;
     }
     
+    private static InputStream getInputStream(StorageIO<DataFile> storage, boolean isTabularData) throws IOException {
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java:1452]: Perhaps call this getOriginalFileInputStream to make it clearer? Also - any reason not to put the storage.open call in this method?

File: src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java [hunk 2]
```diff
@@ -1484,7 +1487,18 @@ public static void validateDataFileChecksum(DataFile dataFile) throws IOExceptio
         try {
             recalculatedChecksum = FileUtil.calculateChecksum(in, checksumType);
         } catch (RuntimeException rte) {
+            logger.log(Level.SEVERE, "failed to calculated checksum, one retry", rte);
             recalculatedChecksum = null;
+            IOUtils.closeQuietly(in);
+            storage = dataFile.getStorageIO();
+            try {
+                storage.open(DataAccessOption.READ_ACCESS);
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java:1495]: If storage.open is part of the get stream call, could you use try with resources here? (I think your code works but having the outer try close the stream you open in the inner try's catch seems fragile. Plus we're slowly shifting to use try with resources in general.)

File: src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 1 above)
Comment (ErykKul) [reply src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]: Done.

File: src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 2 above)
Comment (ErykKul) [reply src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]: I refactored the try-catch blocks to the try-with-resources. I think the code is not only safer but also more readable right now. Thanks!

**Review by qqmyers — APPROVED** [review]
Looks good

**Comment by landreev** [comment]
This is great, merging.
