### PR TITLE
IQSS 10390: Multipid UI Fix

### LINKED ISSUE #10390: MultiPid UI selector incorrect for sub-collections
The existing code doesn't handle the case where a non-default inherited PID Provider exists - the entry shows the default which is not what will be used. This is only an issue in sub-collections (where an inherited PID provider can exist).

**What steps does it take to reproduce the issue?**

* When does this issue occur?

* Which page(s) does it occurs on?

* What happens?

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?
As with other UI selections, the UI should show what will be used (the default or the inherited value if it exists), e.g. 
image

**Which version of Dataverse are you using?**
develop

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: Fixes the issue by adding logic to determine what option will be inherited by a collection - the global default or the value inherited from a parent collection. The PR also addresses the issue with the GET /api/datasets/id/pidGenerator call sometime returning "default" instead of the PidProvider that will be used (as documented in the Guides).

**Which issue(s) this PR closes**:

Closes #10390

**Special notes for your reviewer**: Suggesting we put this in 6.2 to avoid a bug going out.

**Suggestions on how to test this**: Have more than one pid provider configured, create a subcollection and verify that the menu of options on the Dataverse/Edit/GeneralInfo pane shows the options, including one that is either the (default) - if no parent collection has a non-default selection - or (inherited...) option - when a parent/grandparent has an explicit PIDProvider setting. 
Can also call the API call above and verify that it returns a PidProvider id in all cases.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: see screenshot in inssue.

**Is there a release notes update needed for this change?**: no - fixes a bug that hasn't yet been released.

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/api/Datasets.java [hunk 1]
```diff
@@ -4588,7 +4595,12 @@ public Response getPidGenerator(@Context ContainerRequestContext crc, @PathParam
         } catch (WrappedResponse ex) {
             return error(Response.Status.NOT_FOUND, "No such dataset");
         }
-        String pidGeneratorId = dataset.getPidGeneratorId();
+        PidProvider pidProvider = dataset.getEffectivePidGenerator();
+        if(pidProvider == null) {
+            //This is basically a config error, e.g. if a valid pid provider was removed after this dataset used it
+            return error(Response.Status.NOT_FOUND, "No PID Generator found for the give id");
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/api/Datasets.java:4601]: nitpick here - should be "given" and maybe put it in the bundle. Also should we add a test to PidUtilTest?

**Review by sekmiller — CHANGES_REQUESTED** [review]
Just an error label update, and maybe an additional test - see comment.

File: src/main/java/edu/harvard/iq/dataverse/api/Datasets.java (hunk 1 above)
Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/api/Datasets.java]: done

**Review by sekmiller — APPROVED** [review]
Thanks for the updates

**Comment by pdurbin** [comment]
Works fine but I didn't like how (inherited from enclosing Dataverse) and (Default) are squished...

Screenshot 2024-03-27 at 11 34 37 AM
Screenshot 2024-03-27 at 11 36 16 AM

... so I pushed a fix to add spaces in b196f54

Here's the config I tested with:

        -Ddataverse.pid.providers=fake,foo
        -Ddataverse.pid.default-provider=fake
        -Ddataverse.pid.fake.type=FAKE
        -Ddataverse.pid.fake.label=FakeDOIProvider
        -Ddataverse.pid.fake.authority=10.5072
        -Ddataverse.pid.fake.shoulder=FK2/
        -Ddataverse.pid.foo.type=FAKE
        -Ddataverse.pid.foo.label=Foo
        -Ddataverse.pid.foo.authority=10.1234

Tests are passing. Will merge.
