### PR TITLE
IQSS/8276 - skip validation when embargo isn't enabled.

### LINKED ISSUE #8276: File Page menus broken in 5.8 w/o embargo set
**What steps does it take to reproduce the issue?** 
As reported by @pdurbin in slack, trying to delete a file using the edit menu on the file page fails. Further investigation shows that some items in the Access (Citation downloads) and the Edit (Restrict, delete) menus/the form is broken. The underlying issue is 1) that this menu is in the same form as the hidden embargo dialog and when a delete, restrict, etc. option is chosen, the embargo form is validated as well, and 2) that validation attempt ends with a null pointer exception (FWIW nulls are handled w.r.t. attempting to read the setting but there's an error that causes the validation to run and there's eventually an error in trying to convert the null max date to a string).

* When does this issue occur? 
Menus on the file page, only when the MaxEmbargoDurationInMonths setting is not set (or is set to 0 to disable embargoes)

* Which page(s) does it occurs on?
Only on file page. (Which is somewhat strange as the edit menu in the files table on the dataset works and it nominally uses the same code.)

* What happens?
Actions from a menu fail silently in the UI, with a null pointer exception in the log.

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?

**Which version of Dataverse are you using?**
5.8

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**:  This fixes items in the file page menus that are now (v5.8) broken when the new embargo functionality is not enabled (which would be the default). The change avoids an NPE when the empty embargo (from the dialog that isn't shown) is found to be invalid and then getMaxDate() returns null and the code tries to format it for display in the error message (which also wouldn't show).

**Which issue(s) this PR closes**:

Closes #8276

**Special notes for your reviewer**: any ideas as to why the validation runs and caused a problem on the file page but the same menu on the dataset appears to work fine would be welcome. This PR should fix the problem but if there is a difference between the .xhtml code in the two places that stops the overall embargo validation (and potentially the restrict access validation currently being developed) from running, it might be worth adding that to the file page as well.

**Suggestions on how to test this**: Unset the MaxEmbargoDurationInMonths setting and/or set it to 0 and confirm that all entries in the file page access and edit menus work.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**: Could report that this fixes a bug introduced in 5.8 that breaks some actions on the file page menus (see the issue for the list I know of).

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java [hunk 1]
```diff
@@ -360,36 +360,39 @@ public boolean isEmbargoAllowed() {
...
             throws ValidatorException {
-        UIComponent cb = component.findComponent("embargoCheckbox");
-        UIInput endComponent = (UIInput) cb;
-        boolean removedState = false;
-        if (endComponent != null) {
-            try {
-                removedState = (Boolean) endComponent.getSubmittedValue();
-            } catch (NullPointerException npe) {
-                // Do nothing - checkbox is not being shown (and is therefore not checked)
+        if (isEmbargoAllowed()) {
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java:363]: The only change is adding this if (and then indenting the whole method so github shows a big change) which stops validation from running when embargoes are not enabled (and maxEmbargoDate is then null).

**Review by scolapasta — APPROVED** [review]
