### PR TITLE
8903 email subject

### LINKED ISSUE #8903: Missing dataset name in the email subject line
Hi Dataverse team,

We had a question from our community about the notification emails received from the Dataverse system. Some of them include the dataset name in the subject (e.g., dataset created), whereas others do not (e.g., dataset published). See examples in the screenshot.

ExampleEmails

Planning to include the dataset name in the subject line as discussed in the google chat 
https://groups.google.com/g/dataverse-community/c/66l7shA2y7c

notification.email.submit.dataset.subject={0}: Your dataset has been submitted for review
notification.email.publish.dataset.subject={0}: Your dataset has been published
notification.email.publishFailure.dataset.subject={0}: Failed to publish your dataset
notification.email.returned.dataset.subject={0}: Your dataset has been returned
notification.email.workflow.success.subject={0}: Your dataset has been processed
notification.email.workflow.failure.subject={0}: Failed to process your dataset
notification.email.status.change.subject={0}: Dataset Status Change
notification.email.ingestCompleted.subject={0}: Dataset status
notification.email.ingestCompletedWithErrors.subject={0}: Dataset status

and will be submiting the  pull request soon. 

Thanks

### PR DESCRIPTION
**Pull request by JayanthyChengan**
**What this PR does / why we need it**:
Some of the notification emails received from the Dataverse system include the dataset name in the subject (e.g., dataset created), whereas others do not (e.g., dataset published).

So, including the dataset name for those missing in the subject line.

**Which issue(s) this PR closes**:
Closes #8903

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java [hunk 1]
```diff
@@ -32,6 +32,10 @@ public static InternetAddress parseSystemAddress(String systemEmail) {
 
     public static String getSubjectTextBasedOnNotification(UserNotification userNotification, Object objectOfNotification) {
         List<String> rootDvNameAsList = Arrays.asList(BrandingUtil.getInstallationBrandName());
+        String datasetDisplayName = "";
+        if (objectOfNotification != null) {
+            datasetDisplayName = ((Dataset)objectOfNotification).getDisplayName();
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java:37]: Isn't this method called with non-Dataset objectOfNotifcation? which would cause a class cast exception?

File: src/test/java/edu/harvard/iq/dataverse/util/MailUtilTest.java [hunk 2]
```diff
@@ -98,25 +98,25 @@ public void testSubjectRejectFileAccess() {
     @Test
     public void testSubjectCreateDataset() {
         userNotification.setType(UserNotification.Type.CREATEDS);
-        assertEquals("LibraScholar: Your dataset has been created", MailUtil.getSubjectTextBasedOnNotification(userNotification, null));
+        assertEquals("LibraScholar: Dataset \"\" has been created", MailUtil.getSubjectTextBasedOnNotification(userNotification, null));
```
Comment (qqmyers) [inline src/test/java/edu/harvard/iq/dataverse/util/MailUtilTest.java:101]: Just to confirm - you only need empty quotes here because the test dataset doesn't have a display name?

File: src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java (hunk 1 above)
Comment (JayanthyChengan) [reply src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java:37]: @qqmyers - I will check this.

File: src/test/java/edu/harvard/iq/dataverse/util/MailUtilTest.java (hunk 2 above)
Comment (JayanthyChengan) [reply src/test/java/edu/harvard/iq/dataverse/util/MailUtilTest.java:101]: @qqmyers :
The method testSubjectCreateDataset() checks for the email subject after the dataset is created.  
Since Null object is passed from this method `MailUtil.getSubjectTextBasedOnNotification(userNotification, null)` ,  which results in empty displayname.  
Hence _notification.email.create.dataset.subject_ property from bundle.properties constructs like above.
notification.email.create.dataset.subject={0}: Dataset "{1}" has been created

Also the changes in MailUtil.java is made to handle these null objects in test cases.  Please let me know, if I misunderstood your comment.  Thanks

File: src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java (hunk 1 above)
Comment (JayanthyChengan) [reply src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java:37]: @qqmyers : I didn't come across any exception while building the package.

Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java:37]: It wouldn't be a build time issue. If you look at MailUtilServiceBean.getObjectOfNotification(), it can return a Dataset, Datafile, DatasetVersion, etc. I think when you change is called for one of the message types that doesn't have a Dataset objectOfNotification, you'd get a runtime class cast exception. I think just adding `&& objectOfNotification instanceof Dataset` would avoid the problem.

Comment (JayanthyChengan) [reply src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java:38]: @qqmyers  - updated the program

**Review by qqmyers — APPROVED** [review]
Looks good.
