### PR TITLE
IQSS/8367- create apitoken when needed for preview, refactor, add embargo logic

### LINKED ISSUE #8367: In-page preview for draft files shows an error when missing user API token
**What steps does it take to reproduce the issue?**

1. Login to a Dataverse install with previewers installed
2. Verify your account doesn't have a generated API token, or revoke it if it exists
3. Create a new dataset with a file that can be previewed, like an image or PDF
4. After the file is uploaded, visit the file page
5. Note the preview panel error that appears (screenshot below). If you generate an API token, it will load correctly.

* When does this issue occur?

When on a file page for a draft file with an account that does not have an API token generated.

* Which page(s) does it occurs on?

The File view page (file.xhtml).

* What happens?

An error is displayed in the preview panel ("Unable to preview metadata....").

* To whom does it occur (all users, curators, superusers)?

Dataset creators, or anyone that can view a draft file.

* What did you expect to happen?

I expected to see a preview of the file.

**Which version of Dataverse are you using?**

5.8, tested in the Scholars Portal demo environment and Harvard demo.

**Any related open or closed issues to this bug report?**

May be resolved in #8265 - please close if that is the case.

**Screenshots:**

Screen Shot 2022-01-25 at 3 19 41 PM

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: 

When a user tries to preview a protected file (in draft dataset, restricted, or embargoed) and does not have a valid apiToken, the preview would fail to display. We already had logic to create a new token for explore tools when needed (token doesn't exist or expired) - this PR refactors to have the preview pane in the datafile page use the same logic. 

Also - with #8363 merged, the logic needs to be updated to explicitly check for an expired token (previously an expired token would be deleted so the no token and expired token cases were the same). Lastly, in looking through the code, it appears that this code was not updated when embargoes were added so the code would fail to allow previews for an actively embargoed, non-restricted file previewed in a published version. (The problem is that a user who should be able to preview the embargoed file couldn't/it did not expose an embargoed file when it shouldn't.)

**Which issue(s) this PR closes**:

Closes #8367

**Special notes for your reviewer**:

**Suggestions on how to test this**: Create files where an API token is needed to access them (only in draft version, restricted, or embargoed) and try to preview with no api token or an expired token - the preview should now work (and wouldn't with the prior code)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java [hunk 1]
```diff
@@ -340,6 +328,24 @@ public void explore(GuestbookResponse guestbookResponse, FileMetadata fmd, Exter
         }
     }
 
+    public ApiToken getApiToken(User user, boolean createIfNeeded) {
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java:331]: Is createIfNeeded ever false? I don't see any usages where it's false

**Review by sekmiller — COMMENTED** [review]
Looks good in general. I just have one question on the getApiToken method and the branch needs to be updated from develop.

File: src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java (hunk 1 above)
Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java:331]: Not now. I thought it might be useful somewhere/someday to be able to call this to see if a token exists without triggering creation, but I can remove this if that's over-designing.

Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java]: I just went ahead and removed the second param - easy enough for someone to add in the future.

**Review by sekmiller — APPROVED** [review]
Looks good. Thanks
