### PR TITLE
Fix n test series multiple

### LINKED ISSUE #9633: "Series" field needs to be made multiple in the "all fields" sample json in the guide
Note: this needs to be done before 5.14!

The field "series" has been made multiple since 5.13. However, the example "all fields" json file we provide in the guide (`scripts/api/data/dataset-create-new-all-default-fields.json`) still has a single-value entry for it, making the json unimportable, once the soc. sci. metadata block is updated: 
```
            "typeName": "series",
            "multiple": false,
            "typeClass": "compound",
            "value": {
              "seriesName": {
              ...
```
It just needs to be updated the same way we've already updated the file `src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json` (used by the ddi export tests): 
```
           "typeName": "series",
            "multiple": true,
            "typeClass": "compound",
            "value": [ 
              {
                ...
```

Worth noting that we've been through the same issue with the other field that was recently made multiple - productionPlace. Plus there were all sorts of other things that were missed when those 2 fields were updated in their respective blocks that we had to keep fixing. I will open an issue for documenting a checklist of all such things and all the places where things need to be changed. So we can make it 100% the responsibility of the developer, if (God forbid) anyone else ever needs to make another existing single field multiple. (edit: opened #9634)

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:

Fixes the test data and adds an API test to create a new dataset from it. The test data carries a dataset loaded with data for all fields of the metadata blocks enabled by default in an installation.

**Which issue(s) this PR closes**:

Closes #9633

**Special notes for your reviewer**:
None.

**Suggestions on how to test this**:
API test should be executed automatically. If you change the test data to be faulty again locally, you can watch it fail...

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No

**Is there a release notes update needed for this change?**:
No

**Additional documentation**:
None

### CODE REVIEW

**Comment by pdurbin** [comment]
Tests were failing due to 404 downloading Payara. Fixed here: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/commit/b3a99b7d627137aa5ba22a82e05496f23bb31f6a

Then I re-ran the build. Different unrelated error:

"[ERROR] Failures: ", "[ERROR]   FilesIT.testGetFileInfo:1416 JSON path data.label doesn't match.", "Expected: stata13-auto-withstrls.dta", "  Actual: stata13-auto-withstrls.tab", "", "[INFO] ", "[ERROR] Tests run: 202, Failures: 1, Errors: 0, Skipped: 8", 

I'm rerunning the build again.

File: src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java [hunk 1]
```diff
@@ -2,25 +2,59 @@
...
                 .body("data.fields.subject.controlledVocabularyValues[0]", CoreMatchers.is("Agricultural Sciences"));
     }
+    
+    @Test
+    void testDatasetWithAllDefaultMetadata() {
+        // given
+        Response createUser = UtilIT.createRandomUser();
+        assumeTrue(createUser.statusCode() < 300,
+            "code=" + createUser.statusCode() +
+            ", response=" + createUser.prettyPrint());
```
Comment (pdurbin) [inline src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java:37]: This is pretty different than our usual style but whatever. 😄

**Review by pdurbin — COMMENTED** [review]
Looks good and tests are passing (now). I'd click approve but I'll leave that honor to Leonid.

File: src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java (hunk 1 above)
Comment (poikilotherm) [reply src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java:37]: I'm trying to keep to good practice. Creating the user etc is not the test, it's a requirement. So the test shall be aborted if requirements ain't met. Using an assertion for this is not the same, as it claims to make this part to be in scope for testing. 

Also, providing more useful error messages here by also printing the actual status code helps if things go sideways. Most other tests are just creating a lot of noise by always doing the pretty printing thing.

Comment (pdurbin) [reply src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java:37]: Let's talk about it some day.

**Comment by pdurbin** [comment]
I just noticed that you can't publish the dataset due to the license:

Screen Shot 2023-06-16 at 4 26 05 PM

**Comment by kcondon** [comment]
[like]  Condon, Kevin M reacted to your message:
________________________________

**Comment by landreev** [comment]
@pdurbin I can't reproduce the problem above on my dev. node. The json file has the license in it: 
```
"license": {
   "name": "CC0 1.0",
   "uri": "http://creativecommons.org/publicdomain/zero/1.0"
},
```
and when I import it, the dataset ends up with this license, and I can publish it. 
It could be because of how licenses are configured on your dev. node, maybe. I recently made a PR that fixed the handling of the license section by the import API; so I'd like to figure out what's going on. 
But I am fairly positive that this is not related to or caused by anything in this PR.

**Comment by pdurbin** [comment]
False alarm! Sorry for the noise! I just cleared out everything (postgres db, all my docker dev volumes) and rebuilt as of 0032f0e469 and ran `testDatasetWithAllDefaultMetadata` again and the dataset is fine this time. It has a CC0 license and I can publish it.

**Comment by poikilotherm** [comment]
Ain't ephemeral setups great?
