### PR TITLE
only iterate over current files in latest published version

### LINKED ISSUE #7014: CuratePublishedDataCommand fails when files have been deleted
The current code iterates through all files in the dataset, not the latest version and, when it finds one that has no filemetadata for the current version, as part of checking to make sure files haven't been added/deleted between the last published version and the draft, flags it as an error. PR to follow.

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: Fixes the ability to re-publish without updating the version on datasets where files have been deleted in prior versions.

**Which issue(s) this PR closes**:

Closes #7014 

**Special notes for your reviewer**: a flaw in my original logic

**Suggestions on how to test this**: This class is used for the admin only 'Update Current Version' option under the publish menu that is available when there are metadata only changes. That option should work as before for all datasets. The fix is that, prior to this fix, if you have a dataset in, for example, v2 with fewer/different files than v1 had, when you make a metadata update (update the description) for v2 and try to 'Update Current Version' it would fail and after this PR it should work.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: No

**Is there a release notes update needed for this change?**: No

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java [hunk 1]
```diff
@@ -85,18 +85,26 @@ public Dataset execute(CommandContext ctxt) throws CommandException {
...
 
         // Look for file metadata changes and update published metadata if needed
-        for (DataFile dataFile : tempDataset.getFiles()) {
-            List<FileMetadata> fmdList = dataFile.getFileMetadatas();
+        List<FileMetadata> pubFmds = updateVersion.getFileMetadatas();
+        int pubFileCount = pubFmds.size();
+        int newFileCount = tempDataset.getEditVersion().getFileMetadatas().size();
+        if (pubFileCount != newFileCount) {
+            logger.severe("Draft version of dataset: " + tempDataset.getId() + " has: " + newFileCount + " while last published version has " + pubFileCount);
+            throw new IllegalCommandException("Different number of files in draft version", this);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java:93]: English that users can see in the UI (including errors) should be moved to a bundle.

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java [hunk 2]
```diff
@@ -85,18 +85,26 @@ public Dataset execute(CommandContext ctxt) throws CommandException {
...
-            }
             boolean metadataUpdated = false;
-            if (draftFmd != null && publishedFmd != null) {
+            if (draftFmd == null || draftFmd.getDatasetVersion().equals(updateVersion)) {
+                if (draftFmd == null) {
+                    logger.severe("Unable to find latest FMD for file id: " + dataFile.getId());
+                } else {
+                    logger.severe("No filemetadata for file id: " + dataFile.getId() + " in draft version");
+                }
+                throw new IllegalCommandException("Cannot change files in the dataset", this);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java:105]: English should go in the bundle. In addition, since we have the file id, maybe it would be worth exposing it to the user in the error message, if it will help them troubleshoot the problem.

**Comment by qqmyers** [comment]
@pdurbin - yes the comparison of file counts is just a check. Nominally the UI won't show the button to allow this if they are different but the API doesn't have a separate check.

**Comment by pdurbin** [comment]
@qqmyers belt and suspenders. Perfect.

**Comment by kcondon** [comment]
There is currently a bug with the publish version popup, #7051 , so I tested using the API and it worked.
