### PR TITLE
6865 no more deadlocks

### LINKED ISSUE #6865: Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected
Sometimes, but not all the time, when I run the API test suite on my laptop, some of the API tests fail with a 500 response and when I look at server.log I see errors like this:

`Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected`

Here's an example of a failing test but the tests vary:

[ERROR]   FilesIT.testReplaceFileBadJson:898 Expected status code <200> doesn't match actual status code <500>.

Here are a couple more examples from last week, both from the same run:

[ERROR] FileMetadataIT.tearDownDataverse:96 Expected status code <200> doesn't match actual status code <500>.

[ERROR] FilesIT.testReplaceFileBadJson:898 Expected status code <200> doesn't match actual status code <500>.

In tech hours today we discussed how these local failures are probably related to failures we've seen on https://jenkins.dataverse.org

Here's my server.log (renamed so GitHub will take it) from today's run: 
[server.log.txt](https://github.com/IQSS/dataverse/files/4548577/server.log.txt)

### PR DESCRIPTION
**Pull request by scolapasta**
**What this PR does / why we need it**:
It cleans up some indexing code - it extracts the index call that was in the DataverseServiceBean save into separate helper methods that can be called my commands in their onSuccess methods; it also removes the indexing of role related permissions during execute (since the dataverse is indexed in the onSuccess), which appeared to be the cause of the deadlocks we were getting in the tests

**Which issue(s) this PR closes**:

Closes #6865 

**Special notes for your reviewer**:
The Commands that call the save are listed here and whether I added on success call. Please review these decisions carefully, in case I missed something.

CreateDataverseCommand - already had an onSuccess index call - so it was already doubling up
PublishDataverseCommand - already had a call to index the permissions on success
RenameDataverseCommand- added a call to re index object on success
UpdateDataverseCommand - already had a call to index the object and all child datasets (unsure why it needed, but kept same logic it had)
UpdatePermissionRootCommand - added a call to re index object and permissions on success (honestly wasn't sure when this command is needed so went the safe root)

MoveDataverseCommand - indexing is already happening in execute - should be moved to onSuccess, but out of scope for this change

UpdateDataverseDefaultContributorRoleCommand - doesn't need indexing 
UpdateDataverseGuestbookCommand - doesn't need indexing
UpdateDataverseGuestbookRootCommand - doesn't need indexing
UpdateDataverseTemplateRootCommand - doesn't need indexing
UpdateDataverseThemeCommand - doesn't need indexing

**Suggestions on how to test this**:
The straightforward thing to do would be test where each of the above commands are used, as they are the ones that will be affected by these changes. In particular that roles permissions are indexed correctly for CreateDataverseCommand.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
no

**Is there a release notes update needed for this change?**:
no

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java [hunk 1]
```diff
@@ -168,17 +169,8 @@ public Dataverse execute(CommandContext ctxt) throws CommandException {
...
-        } catch (IOException | SolrServerException e){           
-            Dataverse dv = (Dataverse) r;            
-            String failureLogText = "Indexing failed. You can kickoff a re-index of this dataverse with: \r\n curl http://localhost:8080/api/admin/index/dataverses/" + dv.getId().toString();
-            failureLogText += "\r\n" + e.getLocalizedMessage();
-            LoggingUtil.writeOnSuccessFailureLog(this, failureLogText,  dv);
-            return false;
-        }
-        return true;
+    public boolean onSuccess(CommandContext ctxt, Object r) {  
+        return ctxt.dataverses().index((Dataverse) r);
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java:173]: The index dataverse here does not index permissions. Should you be using index((Dataverse) r, true)?

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java [hunk 2]
```diff
@@ -90,20 +90,19 @@ public Dataverse execute(CommandContext ctxt) throws CommandException {
...
-
-        List<Dataset> datasets = ctxt.datasets().findByOwnerId(result.getId());
+        
+        // first kick of async index of datasets
+        // TODO: is this actually needed? Is there a better way to handle
         try {
-            Future<String> indResponse = ctxt.index().indexDataverse(result);
+            Dataverse result = (Dataverse) r;
+            List<Dataset> datasets = ctxt.datasets().findByOwnerId(result.getId());
             ctxt.index().asyncIndexDatasetList(datasets, true);
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java:99]: reindexing datasets may not actually be needed here. (based on the instances where it is called ManageTemplates, Guestbook, etc.)

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdatePermissionRootCommand.java [hunk 3]
```diff
@@ -37,6 +37,13 @@ public Dataverse execute( final CommandContext ctxt) throws CommandException {
 		}
 	}
 
+    @Override
+    public boolean onSuccess(CommandContext ctxt, Object r) {  
+        return ctxt.dataverses().index((Dataverse) r,true);
+    }        
+
+
+    //TODO: Review this as this will never be an instance of Dataset, will it?
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdatePermissionRootCommand.java:46]: This will never be a dataset so we can simplify the code here

File: src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java [hunk 4]
```diff
@@ -91,21 +92,33 @@ public Dataverse save(Dataverse dataverse) {
...
+            indexService.indexDataverse(dataverse);
+            if (indexPermissions) {
+                solrIndexService.indexPermissionsOnSelfAndChildren(dataverse);
+            }
         } catch (IOException | SolrServerException e) {
-            String failureLogText = "Post-save indexing failed. You can kickoff a re-index of this dataverse with: \r\n curl http://localhost:8080/api/admin/index/dataverses/" + savedDataverse.getId().toString();
+            String failureLogText = "Post-save indexing failed. You can kickoff a re-index of this dataverse with: \r\n curl http://localhost:8080/api/admin/index/dataverses/" + dataverse.getId().toString();
             failureLogText += "\r\n" + e.getLocalizedMessage();
-            LoggingUtil.writeOnSuccessFailureLog(null, failureLogText, savedDataverse);
+            LoggingUtil.writeOnSuccessFailureLog(null, failureLogText, dataverse);
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java:116]: Kind of a nit, but there are cases where this isn't being called by onSuccess so the failure message so maybe add to the general log in those cases.

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java (hunk 1 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java:173]: Actually, the index without the boolean (of false) does index the call indePermissionForOneDVObject. 

indexPermissions or (index with true) adds a call to indexPermissionOnSelfAndChildren, but that shouldn't be needed in the case of creating a dataverse.

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java (hunk 2 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java:99]: I think you're right, but I wanted to change as little as possible while surgically fixing the deadlocks. So left this code as it was, but added the TODO.

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdatePermissionRootCommand.java (hunk 3 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdatePermissionRootCommand.java:46]: Similar to last, left as todo and out of scope.

File: src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java (hunk 4 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java:116]: This is a brand new method and all the calls I added are in onSuccess methods. Additionally as a tech design decision, we've said we want all such indexing to be onSuccess, no? So I think it's ok.

Note, that currently not all indexing is actually on success (see MoveDataverse), but changing that was out of scope for this issue).
