### PR TITLE
IQSS/10824 - Add logic to suppress query tool display for non-public files.

### LINKED ISSUE #10824: Query Tools show for restricted files on file page
Query tools are currently on supposed to work for publicly readable data files. On the dataset page, query tool buttons are suppressed for restricted/embargoed/not-yet-released files. On the file page, this doesn't happen.
* What happens?
A configured query tool shows on the file page but fails with a 403.

**Which version of Dataverse are you using?**
6.3+

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?
TBD

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: Stops query tools from displaying on the file page when the file is not public. (Query tools are currently designed only to work with public files).

**Which issue(s) this PR closes**:

Closes #10824

**Special notes for your reviewer**: FWIW: I made the fix such that a theoretical query tool that reads only an aux file would still display. That's different from the DatasetPage check which doesn't address this case. 

**Suggestions on how to test this**: Look for the Ask-the-data query tool on a file that is of the right type to use it but is not yet released, is restricted, is embargoed, etc. and verify that it doesn't show in the list of tools on the file page.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/FilePage.java [hunk 1]
```diff
@@ -305,6 +305,16 @@ private void loadExternalTools() {
             exploreTools = exploreTools.stream().filter(tool ->tool.accessesAuxFiles()).collect(Collectors.toList());
             queryTools = queryTools.stream().filter(tool ->tool.accessesAuxFiles()).collect(Collectors.toList());
             toolsWithPreviews = toolsWithPreviews.stream().filter(tool ->tool.accessesAuxFiles()).collect(Collectors.toList());
+        } else {
+            // Don't list queryTools for non-public files
+            // Note - this logic is not the same as isPubAliclyDownloadable which appears to be true for a draft-only file
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/FilePage.java:310]:
```suggestion
            // Note - this logic is not the same as isPubliclyDownloadable which appears to be true for a draft-only file
```

**Review by pdurbin — APPROVED** [review]
I haven't tested it, but this change makes sense to me.

**Comment by sekmiller** [comment]
@qqmyers when you have a chance can you please get the latest from dev? thanks!
