### PR TITLE
replace ZipInputStream with ZipFile

### LINKED ISSUE #10898: zip files created with an own cloud service are ingested as is
**What steps does it take to reproduce the issue?**

- download multiple files from an own cloud service
  for example [greetings.zip](https://github.com/user-attachments/files/17202191/greetings.zip) and [shapes.zip](https://github.com/user-attachments/files/17202192/shapes.zip) (the individual shape file contain garbage, it is about rezipping)
- upload the zip into a dataset
- the zip is ingested as is with a warning message
- unzip an rezip the files before upload and the result is as expected

**Which version of Dataverse are you using?**

It happens both on 6.2 and 6.4

**Any related open or closed issues to this bug report?**
Not sure but replacing `ZipInputStream` with `ZipFile` might influence the following issues
https://github.com/IQSS/dataverse/issues/7507 
https://github.com/IQSS/dataverse/issues/7352
https://github.com/IQSS/dataverse/issues/2482
https://github.com/IQSS/dataverse/issues/8029
https://github.com/IQSS/dataverse/issues/10591
https://github.com/IQSS/dataverse/issues/9425

**Screenshots:**

Current result on the left, on the right expected result with the files attached above after saving the changes

zip-as-is expected: image

**Are you thinking about creating a pull request for this issue?**
yes

### PR DESCRIPTION
**Pull request by jo-pol**
**What this PR does / why we need it**:

It will no longer fail to upload individual files from a zip downloaded from an ownCloud service.
See issue for further details.

**Which issue(s) this PR closes**:

- Closes #10898

**Special notes for your reviewer**:

You will get less differences when ignoring white space changes:
https://github.com/IQSS/dataverse/compare/develop...DANS-KNAW-jp:dataverse:10898-own-cloud-zips?w=1

Replaced ZipInputStream with ZipFile in:
* CreateNewDataFilesCommand
* ShapefileHandler (abandoned ShapefileHandler constructor with FileInputStream to allow the use of ZipFile)

Additional
* for the new iteration method over zip entries in `CreateNewDataFilesCommand`: extracted methods `filteredZipEntries`, `openZipFile`, `getShortName` and `isFileToSkip` The extracted code is slightly different from the ShapeFileHandler.isFileToSkip but changing behavior is beyond the scope of the issue.  
* introduced some unit tests for `CreateNewDataFilesCommand` or should I call it an integragtion test for the changed classes.
* to allow (or at least simplify) the new unit test, `FileUtil.determineFileType` catches Bag exceptions The method will now return `application/zip` rather than throw. Without catching I would need complex mocking to get a BagitFileHandler via CDI just to test the rest.

**Suggestions on how to test this**:

see issue

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

_updated from comment:_
Unzip during upload now supports more variations of the zip format, including the zip files generated by ownCloud.

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java [hunk 1]
```diff
@@ -323,156 +316,104 @@ public CreateDataFileResult execute(CommandContext ctxt) throws CommandException
...
-
-                        if (zipEntry == null) {
-                            break;
-                        }
-                        // Note that some zip entries may be directories - we
-                        // simply skip them:
-
-                        if (!zipEntry.isDirectory()) {
+                    try (var zipFile = openZipFile(tempFile, charset)) {
+                        for (var entry : filteredZipEntries(zipFile)) {
```
Comment (qqmyers) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java:360]: Can you avoid re opening the zip and getting entries since you already have them?

**Review by qqmyers — APPROVED** [review]
Looks good to me. I'd suggest adding a one-line release note, e.g. Unzip during upload now supports more variations of the zip format, including the zip files generated by ownCloud.

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java (hunk 1 above)
Comment (jo-pol) [reply src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java]: Thought I tried and failed. Thanks for making me retry.

**Comment by stevenwinship** [comment]
Test is failing:

execute_rezips_sets_of_shape_files_from_uploaded_zip – edu.harvard.iq.dataverse.engine.command.impl.CreateNewDataFilesTest

File: src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesTest.java [hunk 2]
```diff
@@ -0,0 +1,261 @@
...
+    public void extract_zip_performance() throws Exception {
+        /*
+         Developed to test performance difference between the old implementation with ZipInputStream and the new ZipFile implementation.
+         Play with numbers depending on:
+         - the time you want to spend on this test
+         - how much system stress you want to examine
+        */
+        var nrOfZipFiles = 20;
+        var avgNrOfFilesPerZip = 300;
+        var avgFileLength = 5000;
```
Comment (jo-pol) [inline src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesTest.java:169]: results:

    ZipFile       :: Total time: 150,909ms; nr of zips 20 total nr of files 6,404; total file size 32,030,650
    ZipInputStream:: Total time: 148,432ms; nr of zips 20 total nr of files 6,211; total file size 31,570,383

**Comment by ofahimIQSS** [comment]
Fix looks good. 
[Testing of 10899.docx](https://github.com/user-attachments/files/17525372/Testing.of.10899.docx)
