### PR TITLE
fix S3 provider priorities

### LINKED ISSUE #10003: #9206 appears to break non-AWS S3 storage when role-based access is used
**What steps does it take to reproduce the issue?**
At QDR, we use storJ as one S3 provider. In 5.14+, it appears that access to storJ is broken. Tracing the issue, it appears that adding the role-based provider option back in as the preferred default in #9206 is the cause. Since we have role-based access set up for AWS S3 stores, it is taking precedence, even for our storJ S3 store which is configured to use profile based access, custom-endpoint, etc.

I'm submitting a PR that will allow role-based access to be turned off per store which will allow those stores to use profiles or static creds.

* When does this issue occur?
When role-based access is configured and some stores, e.g. those from other providers, can't use it.

* What happens?
All accesses to the affected store(s) fail - so file uploads/downloads, thumb accesses, etc. are affected

**Which version of Dataverse are you using?**
5.14+

**Any related open or closed issues to this bug report?**
#9205, #9206
Attn: @orazionelson

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: This PR addresses priority issues that existed between the 3 types of credential providers used by S3 stores. Before - the global role-based creds, if set, would override the per store profile or instance credentials. Now they do not, and static creds won't be ignored if/when a default profile exists in the Unix account running Payara.
The PR also includes removal of a redundant check that the bucket exists that would run for every file access.

**Which issue(s) this PR closes**:

Closes #10003 

**Special notes for your reviewer**: New priority rules are listed in a source comment. As this is a bug fix, it looks to me like the current guides say the right thing about priorities. So I don't see anything to change in the docs (without doing a big rewrite of the whole S3 setup section!). Similarly, since this is a bug fix for a reasonably rare case (role-based access was broken from 4.20 to 5.13, and you have to be using two different S3 providers), I don't know that anything is needed in the release notes.

**Suggestions on how to test this**:
Regression testing that S3 setup works. Depending on how far you want to go, you could check all the combinations of EC2 role based access is/isn't set, the S3 store has a .profile set or not, (the profile actually exists in the .aws/credentials file or not), and the static microprofile config is/isn't set and verify that setting a profile or static creds wins over the role based method, profile wins over static when both are set, setting nothing results in the default profile in the .aws/credentials file being used, etc. (I have tested at QDR that this fix works in the case where role-based creds exist and we have an S3 store that has to use a non-default profile instead.)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java [hunk 1]
```diff
@@ -1181,29 +1183,59 @@ private static AmazonS3 getClient(String driverId) {
...
+            // use, you should not use env vars or system properties to provide these, but 
+            // use the secrets config source provided by Payara.
+            Optional<String> accessKey = config.getOptionalValue("dataverse.files." + driverId + ".access-key", String.class);
+            Optional<String> secretKey = config.getOptionalValue("dataverse.files." + driverId + ".secret-key", String.class);
+            if (accessKey.isPresent() && secretKey.isPresent()) {
+                allowInstanceCredentials = false;
+                AWSStaticCredentialsProvider staticCredentials = new AWSStaticCredentialsProvider(
+                        new BasicAWSCredentials(
+                                accessKey.orElse(""),
+                                secretKey.orElse("")));
```
Comment (poikilotherm) [inline src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:1213]:
```suggestion
                                accessKey.get(),
                                secretKey.get()));
```

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java [hunk 2]
```diff
@@ -1181,29 +1183,59 @@ private static AmazonS3 getClient(String driverId) {
...
+                providers.add(staticCredentials);
+            } else if (s3profile == null) {
+                //Only use the default profile when it isn't explicitly set for this store when there are no static creds (otherwise it will be preferred).
+                s3profile = "default";
```
Comment (poikilotherm) [inline src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:1217]: Why not do this above as else to the `!= null`?

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java [hunk 3]
```diff
@@ -1181,29 +1183,59 @@ private static AmazonS3 getClient(String driverId) {
...
+            }
             // Add all providers to chain - the first working provider will be used
-            // (role-based is first in the default cred provider chain, so we're just
+            // (role-based is first in the default cred provider chain (if no profile or
+            // static creds are explicitly set for the store), so we're just
             // reproducing that, then profile, then static credentials as the fallback)
-            AWSCredentialsProviderChain providerChain = new AWSCredentialsProviderChain(instanceCredentials, profileCredentials, staticCredentials);
+
+            // As the order is the reverse of how we added providers, we reverse the list here
+            Collections.reverse(providers);
```
Comment (poikilotherm) [inline src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:1235]: Instead of reversing, wouldn't it make sense to do the addition in correct order? (so start with role, then go on)

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java [hunk 4]
```diff
@@ -1181,29 +1183,59 @@ private static AmazonS3 getClient(String driverId) {
...
+            }
+            if (s3profile != null) {
+                ProfileCredentialsProvider profileCredentials = new ProfileCredentialsProvider(s3profile);
+                providers.add(profileCredentials);
+            }
+
+            if (allowInstanceCredentials) {
+                // Add role-based provider as in the default provider chain
+                InstanceProfileCredentialsProvider instanceCredentials = InstanceProfileCredentialsProvider.getInstance();
+                providers.add(instanceCredentials);
```
Comment (poikilotherm) [inline src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:1227]:
```suggestion
                providers.add(InstanceProfileCredentialsProvider.getInstance());
```

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java [hunk 5]
```diff
@@ -1181,29 +1183,59 @@ private static AmazonS3 getClient(String driverId) {
...
+                                accessKey.orElse(""),
+                                secretKey.orElse("")));
+                providers.add(staticCredentials);
+            } else if (s3profile == null) {
+                //Only use the default profile when it isn't explicitly set for this store when there are no static creds (otherwise it will be preferred).
+                s3profile = "default";
+            }
+            if (s3profile != null) {
+                ProfileCredentialsProvider profileCredentials = new ProfileCredentialsProvider(s3profile);
+                providers.add(profileCredentials);
```
Comment (poikilotherm) [inline src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:1221]:
```suggestion
                providers.add(new ProfileCredentialsProvider(s3profile));
```

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java (hunk 3 above)
Comment (qqmyers) [reply src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:1235]: Since we have to know if the profile and/or static creds exist before we could add the instance creds at the start of the array, I thought it was cleaner to just reverse than to split the code where the cred providers are looked up from where they are actually created/added to the array.

**Comment by pdurbin** [comment]
It would be nice to review and merge our new S3 tests...

- #10044

... before reviewing, testing, and merging this PR.

**Review by pdurbin — APPROVED** [review]
I haven't tested this but I don't see anything obviously wrong with it. Approved.

**Comment by jp-tosca** [comment]
> It would be nice to review and merge our new S3 tests...
> 
> * [add S3 tests, LocalStack, MinIO #10044](https://github.com/IQSS/dataverse/pull/10044)
> 
> ... before reviewing, testing, and merging this PR.

Do you still think this is the case? @pdurbin

**Comment by pdurbin** [comment]
It's not a hard requirement or anything.

File: src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java [hunk 6]
```diff
@@ -108,14 +111,13 @@ public S3AccessIO(T dvObject, DataAccessRequest req, String driverId) {
...
-            } catch (SdkClientException sce) {
-                throw new IOException("ERROR: S3AccessIO - Failed to look up bucket "+bucketName+" (is AWS properly configured?): " + sce.getMessage());
-            }
+
+            // FWIW: There used to be a check here to see if the bucket exists.
+            // It was very redundant (checking every time we access any file) and didn't do
+            // much but potentially make the failure (in the unlikely case a bucket doesn't
+            // exist/just disappeared) happen slightly earlier (here versus at the first
+            // file/metadata access).
+
```
Comment (landreev) [inline src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java:120]: Good call.

**Comment by landreev** [comment]
Looking good.
