### PR TITLE
6300/6396 additional dataset metadata via search api

### LINKED ISSUE #6300: Retrieve updatedAt, version, and keywords when searching through API
**What we want to achieve**
To retrieve the latest datasets information such as `updatedAt`, `dataset version`, `description`, `authors`, `name`, `keywords` and `dataverse link` through search without the need to perform extra requests. (We believe these heavy operations could be reduced.) 

**Current scenario:** 
When searching for files contained in the latest datasets, I am able to retrieve a list of results. However, it requires for an iteration through the results in order to `get the dataset information based on doi` for each of those results in order to retrieve some of the fields above.

**Desired scenario:**
No extra iterations are necessary

--------

Current example of search output
```
{
                "name": "demo20190123a",
                "type": "dataset",
                "url": "https://doi.org/10.5072/FK2/H1DFMX",
                "global_id": "doi:10.5072/FK2/H1DFMX",
                "description": "demo",
                "published_at": "2019-01-23T16:56:36Z",
                "citationHtml": "Reilly, Grainne, 2019, \"demo20190123a\", <a href=\"https://doi.org/10.5072/FK2/H1DFMX\" target=\"_blank\">https://doi.org/10.5072/FK2/H1DFMX</a>, Demo Dataverse, V1, UNF:6:xR77FQWCFydmL55sRXuD+w== [fileUNF]",
                "identifier_of_dataverse": "demo",
                "name_of_dataverse": "Demo Dataverse",
                "citation": "Reilly, Grainne, 2019, \"demo20190123a\", https://doi.org/10.5072/FK2/H1DFMX, Demo Dataverse, V1, UNF:6:xR77FQWCFydmL55sRXuD+w== [fileUNF]",
                "entity_id": 301815,
                "authors": [
                    "Reilly, Grainne"
                ]
            }
```

--------
An example of what it might be useful
```
{
        "id": 3066,
        "doi": "doi:10.5072/FK2/ML0NCM",
        "publisher": "Demo Dataverse",
        "storageIdentifier": "file://10.5072/FK2/ML0NCM",
        "versionId": 807,
        "versionState": "RELEASED",
        "createdAt": "2016-05-24T15:32:55Z",
        "updatedAt": "2016-05-24T15:35:07Z",
        "title": "Test GeoConnect",
        "authors": [
            "Admin, Dataverse"
        ],
        "contacts": [
            {
                "fullname": "Admin, Dataverse",
                "email": "admin@mailinator.com"
            }
        ],
        "description": {
            "text": "1"
        },
        "subject": [
            "Arts and Humanities"
        ],
        "keywords": [],
        "publication": [],
        "producer": {},
        "relatedMaterial": [],
        "dataSource": [],
        "geographicCoverage": [],
    }
```

Potentially, having the datasetId as part of the search result could also be beneficial.

**What we are currently doing with some of the metadata blocks**
We are mapping metadata blocks to a simpler structure in order to reduce complexity at the client side.

Thanks in advance! We are really enjoying working with Dataverse and collaborating with Dataverse developers

### LINKED ISSUE #6396: dataset version information not returned by Search API results
**API Version**
v. 4.18.1 build 267-a91d370

**Description**
The results returned by Dataverse when an authenticated Search is performed through the Search API are missing vital information to identify the version of the results.

This search is meant to return `published` and `unpublished` data

Current response
```
{
    "status": "OK",
    "data": {
        "q": "test",
        "total_count": 2,
        "start": 0,
        "spelling_alternatives": {},
        "items": [
            {
                "name": "Test",
                "type": "dataset",
                "url": "https://doi.org/10.70122/FK2/B3DD2U",
                "global_id": "doi:10.70122/FK2/B3DD2U",
                "description": "Some test",
                "published_at": "2019-11-21T10:31:07Z",
                "citationHtml": "Nguyen, Tai, 2019, \"Test\", <a href=\"https://doi.org/10.70122/FK2/B3DD2U\" target=\"_blank\">https://doi.org/10.70122/FK2/B3DD2U</a>, Demo Dataverse, V24, UNF:6:3P92OI0LZBPjC03KGIzYdg== [fileUNF]",
                "identifier_of_dataverse": "theam",
                "name_of_dataverse": "Theam Dataverse",
                "citation": "Nguyen, Tai, 2019, \"Test\", https://doi.org/10.70122/FK2/B3DD2U, Demo Dataverse, V24, UNF:6:3P92OI0LZBPjC03KGIzYdg== [fileUNF]",
                "authors": [
                    "Nguyen, Tai"
                ]
            },
            {
                "name": "test",
                "type": "dataset",
                "url": "https://doi.org/10.70122/FK2/21YOAO",
                "global_id": "doi:10.70122/FK2/21YOAO",
                "published_at": "2019-10-08T13:59:26Z",
                "citationHtml": "2019, \"test\", <a href=\"https://doi.org/10.70122/FK2/21YOAO\" target=\"_blank\">https://doi.org/10.70122/FK2/21YOAO</a>, Demo Dataverse, V1",
                "identifier_of_dataverse": "theam",
                "name_of_dataverse": "Theam Dataverse",
                "citation": "2019, \"test\", https://doi.org/10.70122/FK2/21YOAO, Demo Dataverse, V1"
            }
        ],
        "count_in_response": 2
    }
}
```

The problem we find is the fact that it is not possible to know what version of the dataset is each result unless we `citationHtml` or `citation` properties of each item.

**Steps to reproduce**
- Create a dataset or use an existing one
- Make a modification in the dataset, e.g. adding a new file, and **DO NOT** Publish the new version
- Perform an authenticated search, providing your API token, where the dataset just modified appears
 
**Expected behaviour**
- Version information is provided, for instance, `versionState`, and version numbers.

It would be great if it could also return the `id` of the dataset

**Actual Behaviour**
- No information about the dataset is provided

```
{
                "name": "test",
                "type": "dataset",
                "url": "https://doi.org/10.70122/FK2/21YOAO",
                "global_id": "doi:10.70122/FK2/21YOAO",
                "published_at": "2019-10-08T13:59:26Z",
                "citationHtml": "2019, \"test\", <a href=\"https://doi.org/10.70122/FK2/21YOAO\" target=\"_blank\">https://doi.org/10.70122/FK2/21YOAO</a>, Demo Dataverse, V1",
                "identifier_of_dataverse": "theam",
                "name_of_dataverse": "Theam Dataverse",
                "citation": "2019, \"test\", https://doi.org/10.70122/FK2/21YOAO, Demo Dataverse, V1"
            }
```

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**: Adds requested dataset information on requests via the Search API. Does not effect searches used by Search Include Fragment (loading the home page, etc.)

**Which issue(s) this PR closes**: 

Closes #6300 and closes #6396 

**Special notes for your reviewer**:  I ended up not adding indexing for this because the fields requested (create date, update date, data source, related publications, etc. aren't really useful as indexes. I made sure that the DB hits for collection the additional info only occur for retrieval of datasets via the SEARCH API.

**Suggestions on how to test this**: Add additional data to a dataset and see that it is returned via the SEARCH API. Run a search with that will return a draft dataset (while including a key that will give you access to that draft) and see that the version state is DRAFT and the published version is also returned if applicable.

**Does this PR introduce a user interface change?**: No.

**Is there a release notes update needed for this change?**: Not really. Could be mentioned as an enhancement

**Additional documentation**:

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/api/Search.java [hunk 1]
```diff
@@ -136,7 +136,7 @@ public Response search(
                         paginationStart,
                         dataRelatedToMe,
                         numResultsPerPage,
-                        queryEntities
+                        true //SEK get query entities always for search API additional Dataset Information 6300  12/6/2019
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/api/Search.java]: If "true" vs. "false" for `query_entities` has no affect in this pull request, the documentation should be changed to reflect this. Here's a screenshot of how it's documented as of 4.18.1:

Screen Shot 2019-12-06 at 3 05 25 PM

**Review by pdurbin — CHANGES_REQUESTED** [review]
Suggestions for the API Guide:

- [ ] update docs for "query_entities" (true vs. false no longer has an effect)
- [ ] update "Basic Search Example" (or add a new example?) to show the new expected output (I suspect this will help with QA and writing the release notes)

Questions (@sekmiller and I talked about some of these already):

- Are the following fields interesting enough to be made into facets?
    - country
    - state
    - city
    - publisher name
- Are we concerned about performance (new database hits) when "per_page" is set to the max of 1000?
- In the future, can we imagine refactoring the code to take the performance hit at index time instead of query time?

**Comment by pdurbin** [comment]
@sekmiller I can't find the issue I half-remember Vito opening but can you please take a look at the following issue to see if it's easy to add in? To be honest, I think it might be best to have some discussion with the user first. My first thought is that "parent id" (database id of the "owner") feels pretty safe to add. 😄 

- API search with subtree param :add more hierarchy information in result #6354

**Comment by pdurbin** [comment]
Me again. @sekmiller and I just talked about how "city" for example, is already indexed into Solr:

https://github.com/IQSS/dataverse/blob/v4.18.1/conf/solr/7.3.1/schema_dv_mdb_fields.xml#L16

So I guess we should get "city" and friends from Solr (rather than the database) since they're already in there. It should be faster.

**Review by landreev — CHANGES_REQUESTED** [review]
@sekmiller Could you please address the suggestions from @pdurbin, regarding the documentation? (like the part about the query_entities parameter - it makes sense that it probably should say something like "currently hard-coded to always be 'true'", or something similar)
I was surprised initially that you chose not to index anything extra - I generally feel we can afford to index more stuff; but I thought about it for a while and I like the argument that this is not something that we have a use for on the dataverse page; and that in the context of the Search API, we already have the entity instantiated and can get this extra info from it... There may be a counter-argument against allowing the functionality in the Search API and the page search to diverge farther apart... But I feel like this is probably outweighed by not having to force an extra full reindex on everybody unless strictly necessary. 
So I'm ok with this going into QA once the doc request is addressed.

File: src/main/java/edu/harvard/iq/dataverse/api/Search.java (hunk 1 above)
Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/api/Search.java]: I updated the parameter list (removed the reference to query_entities) and added an example with the new data items shown.

**Comment by pdurbin** [comment]
@sekmiller and I just chatted about his recent commits and they're looking to me and are in light with comments by @landreev above as well.

a33bcdd updates the example output which should help QA efforts

dba46e8 mentions the removal of a parameter from the Search API and I added a release note about this in 1278522

I'll send this to QA.

**Review by pdurbin — APPROVED** [review]
