### PR TITLE
JSON Schema creator and validator

### LINKED ISSUE #6978: Query Dataverse for mandatory metadata fields via API
RSpace ELN uses the Dataverse API to submit research data to Dataverse. It has a minimal UI for metadata fields such as title, subject, description, authors, contacts and this works on various Dataverses till now.

One of our RSpace customers has their own Dataverse as well - 4.19. They have configured Dataverse to require additional metadata when submitting a Dataset. RSpace doesn't know these fields are mandatory and submission fails:

`Deposit failed: ERROR2020-06-09T10:58:26ZProcessing failedCouldn't update dataset edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Validation Failed: Producer Name is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Distributor Name is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Description Date is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Keyword Term is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Deposit Date is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]).`

This corresponds exactly to what are the required properties as sent by the Dataverse admin, that are not set by RSpace
- Author - Name
- Contact - Name
- Contact - Email
- Description - Text
- Description - Date
- Keyword - Term
- Producer - Name
- Distributor - Name (In our default templates, this is always the name of the (sub-)dataverse. I'm not sure how this should be handled when a dataset is created from RSpace.)
- Deposit Date (In Dataverse, this is generated by the system.)

If this list never changes, then RSpace could develop a solution where it reads a list of mandatory fields from a configuration file. But if it does change from time to time, it would be great if there was an API method in Dataverse to get a list of mandatory metadata fields .Then, a client could programmatically generate input fields for these properties so that the end-user could make a valid submission.

### LINKED ISSUE #9464: Dataset Json Validation: Update the code to use this schema
This is the second step in addressing: https://github.com/IQSS/dataverse-pm/issues/26

Use this schema to update the code. We currently have a library that checks the JSON schema (wc3provenance schema). As part of this solution we should not feel limited to using our current library. (On the page about the JSON schema there are multiple java library options available for validation.)(10)

### LINKED ISSUE #9465: Dataset Json Validation: Create API endpoints to retrieve a JSON schema
This is the third step in addressing: https://github.com/IQSS/dataverse-pm/issues/26

Create API endpoints to retrieve a JSON schema that also has info about the required meta-data so that we can create a full-fledged validation of a dataset. That API end point has a paramenter that is the dataverse collection that you are targetting for deposit. (10)

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**: Creates a custom json schema for a given Dataverse Collection that can be used to validate a dataset.json file prior to uploading to create the dataset

**Which issue(s) this PR closes**:

Closes #9464 Dataset json validation update code to use schema
Closes #9465 Create api.endpoint for Dataset json validation.
Closes #6978 Query Dataverse for mandatory metadata fields via API 

**Special notes for your reviewer**: The api returns a json string that includes the escape characters. wasn't sure if that that is OK or if I should strip them out before returning

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**: Release notes are included

**Additional documentation**: doc updated to include the new endpoints

https://dataverse-guide--10109.org.readthedocs.build/en/10109/api/native-api.html#retrieve-a-dataset-json-schema-for-a-collection

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ValidateDatasetJsonCommand.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+import java.util.logging.Logger;
+
+/**
+ *
+ * @author stephenkraffmiller
+ */
+@RequiredPermissions(Permission.AddDataset)
+public class ValidateDatasetJsonCommand extends AbstractCommand<String> {
+    
+    private static final Logger logger = Logger.getLogger(GetDatasetSchemaCommand.class.getCanonicalName());
```
Comment (landreev) [inline src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ValidateDatasetJsonCommand.java:24]: Copy-and-paste from the other command, probably.

**Comment by landreev** [comment]
I'm not seeing this discussed, in the pr or the linked issues - sorry if I missed it - but was there a specific reason to only use this validation code in the dedicated "validate" api? - and not always use it in the "create" api as well, before attempting to import the json uploaded by the user? 
(are we just assuming that the attempt to import is validation enough, so there's no reason to spend extra cycles pre-validating? ... and if the user needs to know more details about why it failed, then they can run the validate api? - I may have answered my own question already, but please let me know what you think)

**Comment by landreev** [comment]
Something about the fact that the schema is always created on the fly makes me a little uncomfortable.  It should only change when a) metadatablocks configuration changes for the collection and b) when metadatablocks themselves are updated... so it should be possible to cache; and in many practical cases it will never need to be refreshed. 

I'm not sure where we would cache it and how. So this is probably outside the scope for now.

File: doc/sphinx-guides/source/api/native-api.rst [hunk 2]
```diff
@@ -505,6 +505,51 @@ The fully expanded example above (without environment variables) looks like this
 
 .. note:: Previous endpoints ``$SERVER/api/dataverses/$id/metadatablocks/:isRoot`` and ``POST https://$SERVER/api/dataverses/$id/metadatablocks/:isRoot?key=$apiKey`` are deprecated, but supported.
 
+.. _get-dataset-json-schema:
+
+Retrieve a JSON schema for a Collection
```
Comment (pdurbin) [inline doc/sphinx-guides/source/api/native-api.rst:510]:
```suggestion
Retrieve a JSON Schema for a Collection
```

**Review by pdurbin — COMMENTED** [review]
> Something about the fact that the schema is always created on the fly makes me a little uncomfortable.

I feel the same way. While it's very cool that Dataverse can generate a JSON Schema on the fly for a specific collection, we should supply a static copy of generic JSON Schema in our API Guide. By generic I'm thinking the five standard required fields.

**Review by landreev — APPROVED** [review]
Looks good! (and the Jenkins tests are now passing).

**Comment by pdurbin** [comment]
@sekmiller I'm just repeating these comments from me and Leonid in case you missed them:

> Something about the fact that the schema is always created on the fly makes me a little uncomfortable.

I feel the same way. While it's very cool that Dataverse can generate a JSON Schema on the fly for a specific collection, we should supply a static copy of generic JSON Schema in our API Guide. By generic I'm thinking the five standard required fields.

**Comment by sekmiller** [comment]
@pdurbin, yeah I just added a base schema file yesterday. I will add some logic to see if the collection has any extra required fields before generating on the fly.

File: src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java [hunk 3]
```diff
@@ -232,6 +233,39 @@ public Response addDataverse(@Context ContainerRequestContext crc, String body,
...
+    @GET
+    @AuthRequired
+    @Path("{identifier}/datasetSchema")
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response getDatasetSchema(@Context ContainerRequestContext crc, @PathParam("identifier") String idtf) {
+        User u = getRequestUser(crc);
+
+        try {
+            String datasetSchema = execCommand(new GetDatasetSchemaCommand(createDataverseRequest(u), findDataverseOrDie(idtf)));
+            return ok(datasetSchema);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java:261]: @sekmiller and were talking abouthow we probably want to return just the JSON instead of escaped JSON in our normal "ok... data" data structure.

Jim did this recently in this commit:  9953 - don't wrap linkset in a data element 3a4d8f98053ff726c617a45c5ad15d2f3059c138

Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java]: @sekmiller and I decided to return just the JSON Schema. See 2d3f7ab. This way instead of the \n characters and data...message, you get just what you want:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$defs": {
        "field": {
            "type": "object",
            "required": [
                "typeClass",
...
```

File: src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java [hunk 4]
```diff
@@ -919,5 +932,262 @@ public List<Object[]> getDatasetTitlesWithinDataverse(Long dataverseId) {
...
+        }
+    }
+    
+    private  String datasetSchemaPreface = 
+    "{\n" +
+    "    \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n" +
+    "    \"$defs\": {\n" +
+    "    \"field\": {\n" + 
+    "        \"type\": \"object\",\n" +
+    "        \"required\": [\"typeClass\", \"multiple\", \"typeName\"],\n" +
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java:1104]: We could use the fancy new text blocks here: https://docs.oracle.com/en/java/javase/21/text-blocks/index.html

File: src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java [hunk 5]
```diff
@@ -919,5 +932,262 @@ public List<Object[]> getDatasetTitlesWithinDataverse(Long dataverseId) {
...
+            }
+        }
+        if (mdbHasReqField){
+        retval  += startOfMDB.replace("blockName", mdb.getName());
+        
+        retval += minItemsTemplate.replace("numMinItems", Integer.toString(requiredThisMDB.size()));
+        int count = 0;
+        for (DatasetFieldType dsft:requiredThisMDB ){
+            count++;
+            String reqValImp = reqValTemplate.replace("reqFieldTypeName", dsft.getName());
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java:1052]: I'm sort of wondering why we're starting with a string and doing `replace()` here and there rather than building up a JSON object.

**Review by pdurbin — APPROVED** [review]
Tests are passing. @landreev already approved this. I'm approving it too.

I did leave a question/comment about how we're constructing the JSON. We seem to start with a template (a String) and do `replace` on it here and there. Another approach could be to create a JSON object programatically. Not sure what's best.

I did also add some tests and tweaks some docs. I didn't do any testing apart from running the new tests.

I'm wondering if it's possible to mark fields as required via API. If not, the SPA will surely need this sooner or later.

**Comment by pdurbin** [comment]
@JR-1991 are you thinking the values themselves (Chemistry, Law, etc.) should be returned in the JSON Schema?

That would certainly be more convenient than hitting another API to get them. Thanks again for adding that in this PR:

- #9213

Also, I'm wondering if this PR closes the following issue:

- #6978

I'll go ask. 😄

**Comment by johannes-darms** [comment]
I'm not sure if we should address this in this MR. However, IMHO its crucial that the json schema encodes the correct datatypes as defined within the metadatablock and the API returns data that is valid wrt. to the schema. So it would be nice if these two issues #9494. #9495 were somehow addressed.

**Comment by pdurbin** [comment]
> crucial that the json schema encodes the correct datatypes as defined within the metadatablock

A good example of this is that the geospatial block expects floats for north, south, east, west (latitude and longitude). See this related pull request by @stevenwinship and @landreev merged yesterday:

- #10142

**Comment by JR-1991** [comment]
> @JR-1991 are you thinking the values themselves (Chemistry, Law, etc.) should be returned in the JSON Schema?

Sorry for missing your comment earlier. I believe this addition would be valuable and allow for client-side controlled vocabulary validation.
