### PR TITLE
API: deprecate toggle of superuser status in favor of new idempotent endpoint, update setup-all.sh

### LINKED ISSUE #9887: idempotent API call for making a user a superuser
Hello! I like to report an issue in the docker installation process, User Administration does not exist. Issue related: https://github.com/IQSS/dataverse-docker/issues/78

**What steps does it take to reproduce the issue?**
Dataverse Docker installation
* When does this issue occur?
login with the admin account
* Which page(s) does it occurs on?

* What happens?
The admin account works fine, but it doesn't have administration permissions. 

* To whom does it occur (all users, curators, superusers)?
super user. 

* What did you expect to happen?

login with admin and have admin permission.  (red color user)

**Which version of Dataverse are you using?**
v. 5.13 build 1244-79d6e57

**Any related open or closed issues to this bug report?**
https://github.com/IQSS/dataverse-docker/issues/78

In the thread, there are a solution: 

https://github.com/IQSS/dataverse-docker/issues/78#issuecomment-1549662669

### PR DESCRIPTION
**Pull request by zearaujo25**
**What this PR does / why we need it**:
Adds a new endpoint to make the superuser status change idempotent. 
**Which issue(s) this PR closes**:

- Closes #9887

**Special notes for your reviewer**:
none

**Suggestions on how to test this**:
Integration test

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
no
**Is there a release notes update needed for this change?**:
New endpoint addition
**Additional documentation**:

Preview at https://dataverse-guide--10440.org.readthedocs.build/en/10440/api/native-api.html#set-superuser-status

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java [hunk 1]
```diff
@@ -1035,15 +1035,33 @@ public Response toggleSuperuser(@PathParam("identifier") String identifier) {
 		ActionLogRecord alr = new ActionLogRecord(ActionLogRecord.ActionType.Admin, "toggleSuperuser")
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1035]: I'm just leaving this note at the top but can you please add a release note snippet? Please see https://preview.guides.gdcc.io/en/develop/developers/version-control.html#writing-release-note-snippets

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java [hunk 2]
```diff
@@ -1035,15 +1035,33 @@ public Response toggleSuperuser(@PathParam("identifier") String identifier) {
...
 				.setInfo(identifier);
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1036]: Another note at the top. Can you please document this near https://preview.guides.gdcc.io/en/develop/api/native-api.html#make-user-a-superuser ?

**Review by pdurbin — COMMENTED** [review]
Looks good! Thanks! Please see my comments.

**Comment by pdurbin** [comment]
> I wasn't able to run the integrations tests locally as i keep receiving the java connection refused error

Huh. Please hit me up in https://chat.dataverse.org and I can try to help. I'll point you toward running Dataverse in Docker: https://preview.guides.gdcc.io/en/develop/developers/dev-environment.html#quickstart

Anyway, I know you can't see the results of Jenkins testing this pull request...

- #9916

... but here's a screenshot from https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-10440/1/testReport/edu.harvard.iq.dataverse.api/AdminIT/ that shows your tests (all tests, really) are passing:

Screenshot 2024-03-27 at 7 19 16 PM

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java [hunk 3]
```diff
@@ -1035,15 +1035,33 @@ public Response toggleSuperuser(@PathParam("identifier") String identifier) {
...
 		try {
```
Comment (pdurbin) [inline src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1037]: GitHub doesn't let me leave this comment on the right line but I think we should mark the old toggleSuperuser method as deprecated (in the guides and release note too).

**Review by pdurbin — COMMENTED** [review]
A comment on deprecation.

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java (hunk 2 above)
Comment (zearaujo25) [reply src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1037]: @pdurbin done

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java (hunk 1 above)
Comment (zearaujo25) [reply src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1036]: @pdurbin  done

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java (hunk 3 above)
Comment (zearaujo25) [reply src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1038]: @pdurbin done

File: doc/sphinx-guides/source/api/native-api.rst [hunk 4]
```diff
@@ -5306,13 +5306,34 @@ Example: ``curl -H "X-Dataverse-key: $API_TOKEN" -X POST  "https://demo.datavers
...
-~~~~~~~~~~~~~~~~~~~~~
+Toggle User superuser powers
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 Toggles superuser mode on the ``AuthenticatedUser`` whose ``identifier`` (without the ``@`` sign) is passed. ::
 
     POST http://$SERVER/api/admin/superuser/$identifier
 
+.. note:: this endpoint is deprecated. Use the change superuser status endpoint
+
```
[the remark this answers is not in the document]
Comment (zearaujo25) [reply doc/sphinx-guides/source/api/native-api.rst:5317]: Nice to know! Which versionthis PR willgo? 6.2? I will add just in case the deprecation fo this endpoint!

File: src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java [hunk 5]
```diff
@@ -1525,6 +1525,11 @@ static Response makeSuperUser(String username) {
         return response;
     }
 
+    static Response changeSuperUserStatus(String username, Boolean isSuperUser) {
```
[the remark this answers is not in the document]
Comment (zearaujo25) [reply src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java:1528]: @pdurbin done

File: doc/sphinx-guides/source/api/native-api.rst [hunk 6]
```diff
@@ -5306,13 +5306,34 @@ Example: ``curl -H "X-Dataverse-key: $API_TOKEN" -X POST  "https://demo.datavers
...
+  export USERNAME=jdoe
+  export IS_SUPERUSER=true
+  curl -X PUT "$SERVER/api/admin/superuser/$USERNAME" --data "$IS_SUPERUSER"
+
+The fully expanded example above (without environment variables) looks like this:
+
+.. code-block:: bash
+
+  curl -X PUT "http://localhost:8080/api/admin/superuser/jdoe" --data "true"
+
```
[the remark this answers is not in the document]
Comment (zearaujo25) [reply doc/sphinx-guides/source/api/native-api.rst:5337]: @pdurbin done

File: src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java [hunk 7]
```diff
@@ -895,4 +896,15 @@ private String createTestNonSuperuserApiToken() {
         createUserResponse.then().assertThat().statusCode(OK.getStatusCode());
         return UtilIT.getApiTokenFromResponse(createUserResponse);
     }
+
+    @ParameterizedTest
+    @ValueSource(booleans={true,false})
+    public void testChangeSuperUserStatus(Boolean status) {
```
Comment (pdurbin) [inline src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java:902]: Can you please change this to "testSetSuperuserStatus" as well?

**Review by pdurbin — COMMENTED** [review]
A little more feedback.

File: src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java [hunk 8]
```diff
@@ -1525,6 +1525,11 @@ static Response makeSuperUser(String username) {
         return response;
```
[the remark this answers is not in the document]
Comment (zearaujo25) [reply src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java:1526]: @pdurbin done

File: src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java (hunk 7 above)
Comment (zearaujo25) [reply src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java]: @pdurbin done

File: doc/sphinx-guides/source/api/native-api.rst [hunk 9]
```diff
@@ -5412,13 +5412,35 @@ Example: ``curl -H "X-Dataverse-key: $API_TOKEN" -X POST  "https://demo.datavers
...
+  export SERVER_URL=http://localhost:8080
+  export USERNAME=jdoe
+  export IS_SUPERUSER=true
+  curl -X PUT "$SERVER/api/admin/superuser/$USERNAME" --data "$IS_SUPERUSER"
+
+The fully expanded example above (without environment variables) looks like this:
+
+.. code-block:: bash
+
+  curl -X PUT "http://localhost:8080/api/admin/superuser/jdoe" -d "true"
```
Comment (pdurbin) [inline doc/sphinx-guides/source/api/native-api.rst:5442]: Am I doing something wrong? When I do this...

    curl -X PUT "http://localhost:8080/api/admin/superuser/user4bad9d84" -d "true"

I get this error:

{"status":"ERROR","code":415,"message":"HTTP 415 Unsupported Media Type"}

If it matters, this is my version of curl:

```
$ curl --version
curl 8.1.2 (x86_64-apple-darwin22.0) libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
```

That said, it works fine from AdminIT. 🤔 

But we need it to work from curl. That's how many people will use this API endpoint.

**Review by pdurbin — COMMENTED** [review]
Quick question about curl.

Also, I merged develop into this branch.

File: doc/sphinx-guides/source/api/native-api.rst (hunk 9 above)
Comment (pdurbin) [reply doc/sphinx-guides/source/api/native-api.rst:5442]: It works if you add `-H "Content-Type: application/json"`:

```
pdurbin@air dataverse % curl -X PUT -d true -H "Content-Type: application/json" http://localhost:8080/api/admin/superuser/dataverseAdmin
{"status":"OK","data":{"message":"User @dataverseAdmin set as a superuser."}}
pdurbin@air dataverse % 
pdurbin@air dataverse % curl -X PUT -d false -H "Content-Type: application/json" http://localhost:8080/api/admin/superuser/dataverseAdmin
{"status":"OK","data":{"message":"User @dataverseAdmin removed as a superuser."}}
```

Comment (pdurbin) [reply doc/sphinx-guides/source/api/native-api.rst:5442]: `-H "Content-Type: text/plain"` works as well.

Comment (zearaujo25) [reply doc/sphinx-guides/source/api/native-api.rst:5442]: I will add it to the doc!

**Comment by pdurbin** [comment]
@zearaujo25 and I chatted and we decided on the following:

- For consistency with the settings API, we'll switch to `-X PUT -d true`.
- We know the SPA will someday need the ability to promote and demote superusers (probably under /api/users) but we'll defer this for now.
- Since the toggle API is deprecated as of this PR, we will switch scripts/api/setup-all.sh to use it.
- Phil might switch an API test or two to the new PUT version.
- At some point, we should open an issue to migrate away from the POST version (tech debt).

**Comment by zearaujo25** [comment]
>     * We know the SPA will someday need the ability to promote and demote superusers (probably under /api/users) but we'll defer this for now.

I also would like to add the supersuer feature for the SPA probably will need a restructure of endpoints logic. Since its too early to predict such changes, we opt to defer this feature when its clearer the needs the front end team will need

**Comment by pdurbin** [comment]
> defer this feature when its clearer the needs the front end team will need

Yes, exactly. I did ping @ekraffmiller @GPortas @MellyGray and @GermanSaracca about this in Slack: https://iqss.slack.com/archives/C04MJ76A34Z/p1712942297281699

Screenshot 2024-04-12 at 3 43 39 PM

**Review by pdurbin — APPROVED** [review]
@zearaujo25 this is looking really good. Approved! Thank you!

To whoever does QA, I did a fair amount of testing and poking around. Please at least check that tests are passing and that the docs look ok.
