### PR TITLE
deactivate users

### LINKED ISSUE #2419: User account cannot be disabled/deactivated
In DVN 3.6, a Network administrator could deactivate a user account from the network options. This prevented the user from logging in and has been useful in cases that a dataverse creator left an organisation and should be prevented admin access to the dataverse. Unless this user had a Shibboleth account, the organisation has little control over access to the user's account used for Dataverse. Removing the account altogether would create a hole in existing datasets.

A work-around could be to change the account's password and email address to values that the original user has no access to, but this could conflict with #2170 and does not make clear that an account is disabled.

We have deactivated accounts in our DVN 3.6 installation and plan to clean them up, but we may need to migrate some of them and preferably keep them disabled.

(Discussed on IRC: http://irclog.iq.harvard.edu/dataverse/2015-07-28#i_22050)

### LINKED ISSUE #4356: Login: Cannot delete orcid user due to new constraint violation.
Cannot delete oauth users with latest orcid 2 changes, required a new db table, which delete does not know about:

[2017-12-05T12:52:37.664-0500] [glassfish 4.1] [WARNING] [] [org.eclipse.persistence.session.file:/usr/local/glassfish4/glassfish
/domains/domain1/applications/dataverse-4.8.3/WEB-INF/classes/_VDCNet-ejbPU] [tid: _ThreadID=28 _ThreadName=http-listener-1(1)] [
timeMillis: 1512496357664] [levelValue: 900] [[
  
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.Databas
eException
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "authenticateduser" violates foreign key 
constraint "fk_oauth2tokendata_user_id" on table "oauth2tokendata"
  Detail: Key (id)=(7) is still referenced from table "oauth2tokendata".
Error Code: 0
Call: DELETE FROM AUTHENTICATEDUSER WHERE (ID = ?)
        bind => [1 parameter bound]
Query: DeleteObjectQuery([AuthenticatedUser identifier:@kcorcid])

### LINKED ISSUE #4475: Delete user via API
Hi, I would like to have a  delete button on the Manage Users page in order to exclude an account. Is it possible?

### LINKED ISSUE #5462: Password Reset request throws NPE if email is not in authenticateduser table -  v4.9.4
DV 4.9.4 -> ADA has a test install of the latest release of Dataverse. So I thought I would try it out to see what happens for a password reset request if the email entered is not in authenticateduser table.

The message "If this email is associated with an account, then an email will be sent with further instructions to test_nonexistent_email@gmail.com." is shown in the UI (but without the "Password Reset Initiated" information 'panel' at the top as appears in previous versions).

However, in server.log, it shows that a NullPointerException is thrown (I used the fake email address test_nonexistent_email@gmail.com as it is not in the authenticateduser table) - it seems that not finding the email should be handled more gracefully:

[2019-01-14T15:18:32.256+1100] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean] [tid: _ThreadID=51 _ThreadName=jk-connector(5
)] [timeMillis: 1547439512256] [levelValue: 800] [[
  no user found using test_nonexistent_email@gmail.com]]

[2019-01-14T15:18:32.257+1100] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 154
7439512257] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB PasswordResetServiceBean, method: public edu.harvard.iq.dataverse.passwordreset.PasswordResetInitResponse edu.h
arvard.iq.dataverse.passwordreset.PasswordResetServiceBean.requestReset(java.lang.String) throws edu.harvard.iq.dataverse.passwordreset.PasswordResetException]]

[2019-01-14T15:18:32.257+1100] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1547439512257] 
[levelValue: 900] [[
  
javax.ejb.EJBException
        at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
        at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy351.requestReset(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.__EJB31_Generated__PasswordResetServiceBean__Intf____Bean__.requestReset(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetPage.sendPasswordResetLink(PasswordResetPage.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
        at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
        at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
        at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetServiceBean.requestReset(PasswordResetServiceBean.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 61 more
]]

[2019-01-14T15:18:32.258+1100] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1547439512258] [levelValue: 900] [[
  #{PasswordResetPage.sendPasswordResetLink()}: javax.ejb.EJBException
javax.faces.FacesException: #{PasswordResetPage.sendPasswordResetLink()}: javax.ejb.EJBException
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.faces.el.EvaluationException: javax.ejb.EJBException
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
        ... 43 more
Caused by: javax.ejb.EJBException
        at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
        at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy351.requestReset(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.__EJB31_Generated__PasswordResetServiceBean__Intf____Bean__.requestReset(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetPage.sendPasswordResetLink(PasswordResetPage.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
 at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
        at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
        at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        ... 44 more
Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetServiceBean.requestReset(PasswordResetServiceBean.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 61 more
]]

[2019-01-14T15:18:32.259+1100] [glassfish 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1547439512259] [levelValue: 1000] [[
  javax.faces.el.EvaluationException: javax.ejb.EJBException
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
       at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ejb.EJBException
        at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
        at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy351.requestReset(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.__EJB31_Generated__PasswordResetServiceBean__Intf____Bean__.requestReset(Unknown Source)
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetPage.sendPasswordResetLink(PasswordResetPage.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
        at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
        at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
        at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        ... 44 more
Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.passwordreset.PasswordResetServiceBean.requestReset(PasswordResetServiceBean.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 61 more
]]

### LINKED ISSUE #7575: Unable to merge a user when they have initiated a password reset
This issue was found in version 5.1.1 in Scholars Portal Dataverse. Apologies in advance if this has since been resolved!

When using the "merge user" API, the command appears to fail if the user has initiated a password reset.

The following messaging was in the `server.log` file, which suggests some data connected to the user is still in the `passwordresetdata` table and is preventing the merge:

```
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "builtinuser" violates foreign key constraint "fk_passwordresetdata_builtinuser_id" on table "passwordresetdata"
  Detail: Key (id)=(2232) is still referenced from table "passwordresetdata".
Error Code: 0
```

### PR DESCRIPTION
**Pull request by pdurbin**
Note: This feature was originally called "disable users" and was later renamed to "deactivate users" so you will likely see mention of "disable" instead of "deactivate" below.

**What this PR does / why we need it**:

The people who run a Dataverse installation want the ability to deal with users that should be deleted (#4475), disabled (#2419), or otherwise reduced from a normal, active account.

New API endpoints:

- This pull request delivers "disable user account" functionality (via API) as well as documentation in the guides that provides details about the consequences this action. Please note that there is no way to "undisable" an account.
- This pull request also provides a new "Show User Traces" API endpoint. The thinking behind showing the traces is that the "delete" functionality only gives vague messages about why the delete cannot proceed ("the user has created Dataverse object(s)", for example) but now the details are exposed.
- Finally, this pull request includes an API for "remove all roles" that does the equivalent of the button in the superuser dashboard. It was useful in testing (and is included in new tests).

Changes to existing API endpoints:

- The "merge user" API has a new rule: "User accounts can only be merged if they are either both enabled or both disabled." In addition, #7575 ("Unable to merge a user when they have initiated a password reset") was fixed.
- The "delete" API is largely unchanged. An untracked bug was fixed whereby an account can now be deleted even if it has data in the OAuth2TokenData database table. In addition, the delete command now warns that an account cannot be delete if it has been used to create saved searches.
- The "show user as JSON" API is the same except that two new fields have been added: disabled (a boolean), and disabledTime (a timestamp).

**Which issue(s) this PR closes**:

- Closes #2419 User account cannot be disabled/deactivated
- Closes #4475 Delete user via API
- Closes #5462 Password Reset request throws NPE if email is not in authenticateduser table
- Closes #7575 Unable to merge a user when they have initiated a password reset
- Closes #4356 Login: Cannot delete orcid user due to new constraint violation

Note that #4475 was the issue we estimated during sprint planning (large) but as discussion went on we took several turns. We considered the idea that deleting users could mean the database tables would point toward some sort of anonymous or deleted user. We considered promoting merging as a solution for getting rid of users. In the end, we decided to offer the ability to disable a user.

**Special notes for your reviewer**:

We don't have a way to write browser-based tests (#4202) so I didn't include any tests for testing that accounts are disabled via browser/session.

I'm somewhat concerned that we don't include the ability to "undisable" an account but didn't work on this because it doesn't seem strictly necessary and we haven't discussed what that account would be like (permissions, for example, are blown away by the "disable" command). Perhaps this could be added in a future pull request, especially if there's demand for it. In practice it means that if you disable the account of someone using HarvardKey, for example, that person can no longer use HarvardKey to log into a Dataverse installation.

I added the ability to disable a user by both "identifier" (username) and database id because I was looking at the "delete" user code but I'm not sure if this needed or not. We could probably get away with just delete by username.

If you're interested in more discussion on the guides (which served as a spec), see pull request #7585. The branch behind that pull request was eventually merged into this one.

**Suggestions on how to test this**:

First, I tested what I could locally by mocking Shib, and OAuth, but I recommend testing these with real systems. I did not test OIDC accounts at all (I don't know how to) but from talking to Oliver it seems like it should take the same code path as OAuth.

Generally speaking, the guides should be helpful in understanding the expected behavior. See especially bullets under "Disabling a user with this endpoint will:..." One note on "Disabling a user with this endpoint will keep:..." is that disabled users should still show up as contributors under the versions tab of a dataset. I imagine the bulk of the testing involves investigating each of those bullets.

As mentioned above, there's a new rule with regard to merging accounts: "User accounts can only be merged if they are either both enabled or both disabled." The pull request includes automated tests for this but it wouldn't hurt to test it.

As mentioned above, there are two specific bugs that were fixed:

- Closes #5462 Password Reset request throws NPE if email is not in authenticateduser table
- Closes #7575 Unable to merge a user when they have initiated a password reset

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

Yes, when accounts are disabled, users will see "Sorry, your account has been disabled. If you believe this is an error, please contact support for assistance." There is a screenshot below. The message should be identical for Builtin, Shib, OAuth, and OIDC accounts.

account-disabled

If an OAuth account attempts the "convert" process on a disabled account, it should fail with "Your account can only be converted if you provide the correct username and password for your existing account. If your existing account has been disabled by an administrator, you cannot convert your account." The screenshot below shows the old message before it was updated.

oauth

If a Shib/Institutional account attempts the "convert" process on a disabled account, it should fail with "Validation Error - Your account can only be converted if you provide the correct password for your existing account. If your existing account has been disabled by an administrator, you cannot convert your account." The screenshot below shows the old message before it was updated.

shib

**Is there a release notes update needed for this change?**:

Yes, included.

**Additional documentation**:

None.

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java [hunk 1]
```diff
@@ -1686,7 +1714,7 @@ public Response submitDatasetVersionToArchive(@PathParam("id") String dsid, @Pat
 			// DataverseRequest and is sent to the back-end command where it is used to get
 			// the API Token which is then used to retrieve files (e.g. via S3 direct
 			// downloads) to create the Bag
-            session.setUser(au);
+            session.setUser(au); // TODO: Stop using session. Use createDataverseRequest instead.
```
Comment (sekmiller) [inline src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1717]: Is this still a TODO?

Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/api/Admin.java:1717]: This is a future TODO that I discussed with @qqmyers . I didn't want to mess with this SubmitToArchive (and ask for QA to re-test it) but it's somewhat of session.setUser, I feel. As I indicated, createDataverseRequest is what we usually do in this case.

File: doc/sphinx-guides/source/api/native-api.rst [hunk 2]
```diff
@@ -3075,9 +3079,104 @@ Deletes an ``AuthenticatedUser`` whose ``id``  is passed. ::
...
+
+.. note:: See :ref:`curl-examples-and-environment-variables` if you are unfamiliar with the use of export below.
+
+.. code-block:: bash
+
+  export API_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
+  export SERVER_URL=http://localhost:8080
+  export USERNAME=jdoe
+
+  curl -H "X-Dataverse-key:$API_TOKEN" -X POST $SERVER_URL/api/admin/authenticatedUsers/$USERNAME/disable
```
Comment (poikilotherm) [inline doc/sphinx-guides/source/api/native-api.rst:3099]: Why would it be necessary to use a token here? IIRC all other endpoints in admin API are used without these tokens. For security, you can either use it on localhost only or add the `?unblock-key=...` feature. This might cause confusion.

Comment (pdurbin) [reply doc/sphinx-guides/source/api/native-api.rst:3099]: It's because DisableUserCommand calls RevokeAllRolesCommand, which requires superuser permissions.

Comment (scolapasta) [reply doc/sphinx-guides/source/api/native-api.rst:3099]: We should think of a strategy here to not require a token for an admin api, as I agree it's confusing. Generally (I think this is true), things in the admin API do not call commands, as commands require users. I think that has been a good model (or we need to decide on having commands that don't require users, but that feels dangerous).

File: src/main/resources/db/migration/V5.3.0.3__4475-disable-users.sql [hunk 3]
```diff
@@ -0,0 +1,4 @@
+-- Users can be disabled.
```
Comment (sekmiller) [inline src/main/resources/db/migration/V5.3.0.3__4475-disable-users.sql:1]: There is another script named V5.3.0.3 for expanded dataset field validation. How do we go about resolving? (Having deployed the other I'm getting a flyway script error when I try to deploy this branch.)

Comment (pdurbin) [reply src/main/resources/db/migration/V5.3.0.3__4475-disable-users.sql:1]: I'm happy to let @scolapasta make a ruling.

Comment (scolapasta) [reply src/main/resources/db/migration/V5.3.0.3__4475-disable-users.sql:1]: Since expanded dataset field validation is already in QA, let's change this one to be after.

Comment (pdurbin) [reply src/main/resources/db/migration/V5.3.0.3__4475-disable-users.sql]: Ok, changed to be after in e73c43b70.

**Review by sekmiller — APPROVED** [review]
I don't have any objections. I'm a little embarrassed that I spelled Authenticated wrong in a method name that is being carried forward in perpetuity, and there may be something to be done about removing groups and group role assignments in tandem, but those are quibbles.

File: src/main/java/edu/harvard/iq/dataverse/DataFile.java [hunk 4]
```diff
@@ -57,6 +57,10 @@
 @NamedQueries({
 	@NamedQuery( name="DataFile.removeFromDatasetVersion",
 		query="DELETE FROM FileMetadata f WHERE f.datasetVersion.id=:versionId and f.dataFile.id=:fileId"),
+        @NamedQuery(name = "DataFile.findByCreatorId",
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/DataFile.java:60]: I noticed these are repeated for all the dvobjects? Could we simplify by just getting from dvobject? (is there a case for individually? it just seems a little over kill)

File: src/main/java/edu/harvard/iq/dataverse/DataverseSession.java [hunk 5]
```diff
@@ -210,6 +221,9 @@ public void dismissMessage(BannerMessage message){
     }
     
     public void configureSessionTimeout() {
+        if (user instanceof GuestUser) {
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/DataverseSession.java:224]: Could you explain what this adds?

File: src/main/java/edu/harvard/iq/dataverse/UserNotificationServiceBean.java [hunk 6]
```diff
@@ -103,6 +103,10 @@ public void sendNotification(AuthenticatedUser dataverseUser, Timestamp sendDate
     }
 
     public void sendNotification(AuthenticatedUser dataverseUser, Timestamp sendDate, Type type, Long objectId, String comment, AuthenticatedUser requestor, boolean isHtmlContent) {
+        if (dataverseUser.isDisabled()) {
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/UserNotificationServiceBean.java:106]: I don't think we need this: disabled users will have no roles. Let's save a few lines of code.

File: src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java [hunk 7]
```diff
@@ -215,6 +220,7 @@ public void deleteAuthenticatedUser(Object pk) {
                 em.remove(confirmEmailData);
             }
             userNotificationService.findByUser(user.getId()).forEach(userNotificationService::delete);
+            em.createNativeQuery("delete from OAuth2TokenData where user_id =" + user.getId()).executeUpdate();
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java:223]: can you move this to a named query?

File: src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserServiceBean.java [hunk 8]
```diff
@@ -79,6 +79,8 @@ public BuiltinUser find(Long pk) {
     public void removeUser( String userName ) {
         final BuiltinUser user = findByUserName(userName);
         if ( user != null ) {
+            // TODO: Consider adding a cascade delete instead.
+            passwordResetService.deleteResetDataByDataverseUser(user);
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserServiceBean.java:83]: any reason not to do cascade delete now? seems straightforward and less tech debt.

File: src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java [hunk 9]
```diff
@@ -14,4 +14,6 @@
 
     public boolean isSuperuser();
 
+    public boolean isDisabled();
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java:17]: fyi, it is now possible to add a default implementation of the method and so not have to override in subclasses if they use the default.

File: src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java (hunk 7 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java:223]: and actually maybe better, why not use  a cascade here too?

**Review by scolapasta — COMMENTED** [review]
Very extensive - nice! Overall made some small comments.

The two bigger things I have questions on are:
• needing a token for an admin API. I don't think we should do this - if you need a token, we should move to a reachable API. If we want to keep in admin we should refactor, probably by moving the code to a shared place for the command and outside. We likely do want this to be a publicly accessibly (for superuser) API someday, but I still think we should have the code reflect it's current way of being, again admin API means don't use commands that require checking user. (this does complicate things a little, because then we'd probably want to add something to the actionlogrecord for this, since we wouldn't get that for free from the Command. I don't know, there's no simple / ideal path, but the current state just seems to be not ideal.
The 2nd is whether we actually want the system to care about disabled users in a way that's different (from a UI perspective) from when you are actually deleted. Obviously it should not allow reusing a username / email, BUT I could see it be that if you try to login and are disabled it just says "user does not exist" as if it had been deleted. (that's in line with when I was suggesting remove rows from authenticated lookup). 

Let's find some time to discuss these things over slack (or possibly a call) and include any interested parties.

**Comment by scolapasta** [comment]
> needing a token for an admin API. I don't think we should do this - if you need a token, we should move to a reachable API. If we want to keep in admin we should refactor, probably by moving the code to a shared place for the command and outside. We likely do want this to be a publicly accessibly (for superuser) API someday, but I still think we should have the code reflect it's current way of being, again admin API means don't use commands that require checking user. (this does complicate things a little, because then we'd probably want to add something to the actionlogrecord for this, since we wouldn't get that for free from the Command. I don't know, there's no simple / ideal path, but the current state just seems to be not ideal.

So I've been thinking more about this. There's room for a lot of cleanup here with how admin api should work with commands and if there should be a SystemUser.java class for example. @pdurbin can you verify for me that none of these commands that are called store the user anywhere? (except probably actionLogRecord)?)

At the very least, let's use some code that harvesting uses (thanks @landreev) and not require a token - it calls a method in the AuthenticationServiceBean:
```authSvc.getAdminUser(); ```

(this gets the first by id superuser - which we should eventually make work better, but is fine for now to take a little debt).

File: src/main/java/edu/harvard/iq/dataverse/DataverseSession.java (hunk 5 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/DataverseSession.java:224]: Right. This is the thing @landreev and I talked about in Slack: https://iqss.slack.com/archives/C010LA04BCG/p1613509511062000

In short, when `configureSessionTimeout` was added, it was always put in after `setUser`, with the implication that we're now dealing with an AuthenticatedUser (or at least a non-GuestUser).

That is to say, all over the code, you'll see these two lines execute one after the other:

```
setUser(user);
configureSessionTimeout();
```

Prior to this pull request `configureSessionTimeout` could assume it has a non-GuestUser and would go ahead an lengthen the session. Now we can't make that assumption since `setUser` returns early if the user is disabled, with the result that the session contains a GuestUser rather than an AuthenticatedUser.

File: src/main/java/edu/harvard/iq/dataverse/UserNotificationServiceBean.java (hunk 6 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/UserNotificationServiceBean.java]: Agreed. I was just being paranoid, I guess. Removed in 8f08f7b31.

File: src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java (hunk 7 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java:223]: I need to refresh myself on the proper setup of cascades, but sure.

File: src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserServiceBean.java (hunk 8 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserServiceBean.java:83]: The only reason is that I hadn't set up a cascade in a while. I'll look at some examples and see what I can do.

File: src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java (hunk 9 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java:17]: Gotcha. Do you want me to try to make this change for isDisabled? (I'd rather not mess around with isAuthenticated and isSuperuser right now).

**Review by pdurbin — COMMENTED** [review]
@scolapasta thanks for the feedback. Here are some comments on it.

File: src/main/java/edu/harvard/iq/dataverse/DataFile.java (hunk 4 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/DataFile.java:60]: ok.

File: src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java (hunk 9 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java:17]: Yeah, let's do it. It's not important enough to hold anything up, but should a good tool to use for these kinds of things in the future.

File: src/main/java/edu/harvard/iq/dataverse/DataverseSession.java (hunk 5 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/DataverseSession.java:224]: I just checked and see what you're saying; we *always* call configureSessionTimeout after setUser. Why don't we just move that logic into setUser then? (and it would be after the early return). We can then not have to remember to call it if we add a setUser again somewhere else.

File: src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java (hunk 9 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/authorization/users/User.java]: Done in 23b8bf638.

File: src/main/java/edu/harvard/iq/dataverse/DataverseSession.java (hunk 5 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/DataverseSession.java:224]: @landreev do you have any objection to what @scolapasta is proposing above?

Comment (landreev) [reply src/main/java/edu/harvard/iq/dataverse/DataverseSession.java:224]: I don't remember much about that code (or what exactly I was thinking when I implemented it that way). But yes, it looks like it would be possible - to just call it from inside setUser().

Comment (landreev) [reply src/main/java/edu/harvard/iq/dataverse/DataverseSession.java:224]: P.S. as long as we make sure it's called from inside this `if` block in setUser(): 
```
FacesContext context = FacesContext.getCurrentInstance();
if(context != null) {
   ...
}
```
... or otherwise in a way that's not going to result in a null pointer if it's called from a place where faces context is unavailable...

File: doc/sphinx-guides/source/api/native-api.rst (hunk 2 above)
Comment (pdurbin) [reply doc/sphinx-guides/source/api/native-api.rst:3099]: Fixed in d6e11732c (using authSvc.getAdminUser as suggested elsewhere).

File: src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java (hunk 7 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java]: Fixed in 8afbf5e92.

File: src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserServiceBean.java (hunk 8 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserServiceBean.java]: Fixed in 6e61841cb.

File: src/main/java/edu/harvard/iq/dataverse/DataverseSession.java (hunk 5 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/DataverseSession.java]: Thanks, all. Fixed in 610e9ca32.

**Comment by pdurbin** [comment]
> needing a token for an admin API

Fixed:

d6e11732c run disable user command without superuser API token

With regard to where the superuser is stored/logged, I believe it's only in the ActionLogRecord.

> The 2nd is whether we actually want the system to care about disabled users in a way that's different (from a UI perspective) from when you are actually deleted.

I'd consider this some sort of phase 2 or future effort.

Here are some other fixes I put in the branch:

610e9ca32 merge configureSessionTimeout into setUser
8afbf5e92 remove oauth2tokendata with a cascade 
6e61841cb remove password reset data with cascade

I'm putting this back into review.

**Review by scolapasta — APPROVED** [review]
Good changes - I'll approve.

I did notice there are some calls in deleteAuthenticatedUser that do seem like they could also become cascade... they were there before, so we can consider out of scope, but @pdurbin can you take a look and see if this is correct? And if so open up a new issue for that as it could be a future tech debt cleanup.

**Comment by pdurbin** [comment]
Sure, I just opened this issue:

-  more cascade delete for deleteAuthenticatedUser #7652

**Comment by kcondon** [comment]
Issues found so far:
1. Disable user endpoint doesn't care what permissions api key has but requires a key, otherwise http 405. Thought discussion in pr and that it is an admin api would not require a key.
2. After disabling a user, some users cannot be found in assign roles ui, autocomplete. Also will not allow assigning role to fully typed existing user that is not disabled but doesn't appear in autocomplete list. Not other users do appear in auto complete list and the ones that do not appear do appear in dashboard, users. Last, this does not happen on develop branch.

**Comment by pdurbin** [comment]
@kcondon thanks for all the testing! I was able to reproduce almost all of the issue you found and put in various fixes, detailed below.

@scolapasta @landreev please see the note about getUser below. I'm moving this to code review.

> 1. Disable user endpoint doesn't care what permissions api key has but requires a key, otherwise http 405. Thought, based on discussion in pr and that it is an admin api, that it would not require a key.

I can't reproduce this and the automated tests do not use a token. However, the docs were incorrect and showed the use of an API token so I corrected them in abb8be01e.

> 2. After disabling a user, some existing users cannot be found in assign roles ui, autocomplete.

As far as I can tell, autocomplete for assigning roles was completely broken in the branch, due to me botching the query. Fixed in 0efee2810.

> 3. Attempting to remove roles using api endpoint with a key that does not have sufficient permissions gives incomplete/confusing error message: {"status":"ERROR","message":"Unable to revoke all roles: null"}

The error wasn't being bubbled up from the command. Fixed in 3713104c3.

> 4. On manage users page, disabled user still appears, can make a superuser. Suggestion, make authentication type for disabled user, disabled.

As discussed in Slack, we're putting the word "disabled" in parentheses. In addition the JSON output from /api/admin/list-users now contained "deactivated" and "deactivatedTime". This code and the dashboard code are related. Fixed in c2b7b0aaf.

> 5. Disable user if logged in, remains logged in and can edit account info. Update: this happens with delete user too. For disabled case, reenables it but without some stuff, for delete it adds a new account on save!

Fixed in 3e59e70b6. Now the getUser code checks if the user in the session still exists and is not disabled.

Concern has been expressed that modifying getUser like this could result in a performance problem. A quick benchmark indicates that if you navigate to the homepage, sign up for an account, and then create a dataverse, the getUser method is called 264 times.

> 6. Can log in using builtin disabled user account, if that disabled user edited their account info in step 5

Fixed in 3e59e70b6, the same getUser fix mentioned above.

> 7. Can merge the same account into itself with result being user is deleted. In 5.3, throws constraint error, though could use better error msg.

Indeed, the user was deleted. This bug is probably preexisting in released versions. Fixed in 4f81fbde7.

> 8. Convert oauth (github) account link/page with same email as a newly created, enabled builtin account results in 500 error: 

I can't reproduce this. I'm on 4f81fbde7.

> 9. Convert oauth (github) account with same email as disabled builtin account, sends user to convert account form, then when enter account to convert, provides both a success and failure message and oauth is logged in. Checking account status after shows merge didn't happen.

Fixed in fbded77e1 to prevent deactivated accounts from being converted to OAuth accounts.

> 10. Convert shib account works with enabled builtin but on disabled builtin, gives both success and failure though it actually fails. Should check and prevent submitting account for conversion as ui above.

Fix in fdc9cbe44 to prevent deactivated accounts from being converted to Shib accounts.

**Comment by scolapasta** [comment]
> Concern has been expressed that modifying getUser like this could result in a performance problem. A quick benchmark indicates that if you navigate to the homepage, sign up for an account, and then create a dataverse, the getUser method is called 264 times.

This is what I was worried about, 264 queries for this is not great. What about this - getUser(boolean) (and getUser() calls that with false). With true it calls the query, with false just returns the user. And that way you can target its use to only the places where we need to protect for this - user actions, in the command engine when checking permissions, etc.

**Comment by pdurbin** [comment]
@scolapasta sure, implemented in d0191c3

We now call the more expensive version if the user tries to go to the account page (which logs them out) of if the user tries to execute a command.

The command I played with the most was "create dataverse" since in prod and most of our dev environments, all authenticated users can create dataverses in root. Here's how the the error looks (the only difference for deleted users is that it says "deleted" instead of "deactivated"):

Screen Shot 2021-03-18 at 1 50 26 PM

**Comment by pdurbin** [comment]
The post at https://groups.google.com/g/dataverse-dev/c/wh3m55EGOPU/m/Mij-l0SlAQAJ just reminded me about #4356 about oauth2tokendata which has also been fixed by this pull request (mostly recently touched in 8afbf5e). So I added it to the list of issues above that this pull request closes.

File: src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java [hunk 10]
```diff
@@ -215,7 +218,21 @@ private DvObject getRetType(Object r){
...
+                    logger.fine("submit method found user no longer exists (was deleted).");
+                    throw new CommandException(BundleUtil.getStringFromBundle("command.exception.user.deleted", Arrays.asList(aCommand.getClass().getSimpleName())), aCommand);
+                } else {
+                    if (auFreshLookup.isDeactivated()) {
+                        logger.fine("submit method found user is deactivated.");
+                        throw new CommandException(BundleUtil.getStringFromBundle("command.exception.user.deactivated", Arrays.asList(aCommand.getClass().getSimpleName())), aCommand);
+                    }
+                }
+            }
+
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java:235]: I think we can simplify and remove this - there is already a DataverseRequest associated with this call to the command and that should be enough, as long as we also change the one place where it gets the user from the session in DataverseRequestService to call the new getUser(true) verson of that method.
```
   @PostConstruct
    protected void setup() {
        dataverseRequest = new DataverseRequest(dataverseSessionSvc.getUser(), request);
    }
```

**Review by scolapasta — CHANGES_REQUESTED** [review]
One suggested change related to getUser (which can simplify the code) and a few other minor questions / notes that may or may not need to be acted on. @pdurbin can you review and let me know what you think?

File: doc/sphinx-guides/source/api/native-api.rst [hunk 11]
```diff
@@ -3055,6 +3055,8 @@ Example: ``curl -H "X-Dataverse-key: $API_TOKEN" -X POST http://demo.dataverse.o
 
 This action moves account data from jsmith2 into the account jsmith and deletes the account of jsmith2.
 
+Note: User accounts can only be merged if they are either both non-deactivated or both deactivated. See :ref:`deactivate a user<deactivate-a-user>`.
```
[the remark this answers is not in the document]
Comment (pdurbin) [reply doc/sphinx-guides/source/api/native-api.rst:3058]: "Active" is the opposite of "inactive". Is "active" also the opposite of "deactivated"? Maybe. I felt that "non-deactivated" is more accurate.

File: src/main/java/edu/harvard/iq/dataverse/DataversePage.java [hunk 12]
```diff
@@ -695,7 +695,7 @@ public String save() {
 
         } catch (CommandException ex) {
             logger.log(Level.SEVERE, "Unexpected Exception calling dataverse command", ex);
-            String errMsg = create ? BundleUtil.getStringFromBundle("dataverse.create.failure") : BundleUtil.getStringFromBundle("dataverse.update.failure");
+            String errMsg = create ? ex.getLocalizedMessage() : BundleUtil.getStringFromBundle("dataverse.update.failure");
```
[the remark this answers is not in the document]
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/DataversePage.java:698]: Please see d0191c394 for how ex.localized message comes from EjbDataverseEngine with (for example) ` command.exception.user.deactivated={0} failed: User account has been deactivated.`

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java [hunk 13]
```diff
@@ -663,6 +695,10 @@ public Response builtin2shib(String content) {
 						password);
 				if (authenticatedUser != null) {
 					knowsExistingPassword = true;
+                                        if (builtInUserToConvert.isDeactivated()) {
```
[the remark this answers is not in the document]
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/api/Admin.java:698]: You're right. It could be. I'm testing moving it up.

File: src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MergeInAccountCommand.java [hunk 14]
```diff
@@ -57,7 +58,15 @@ public MergeInAccountCommand(DataverseRequest createDataverseRequest, Authentica
...
     @Override
     protected void executeImpl(CommandContext ctxt) throws CommandException {
-        
+
+        if (consumedAU.getId() == ongoingAU.getId()) {
+            throw new IllegalCommandException("You cannot merge an account into itself.", this);
+        }
+
+        if (consumedAU.isDeactivated() && !ongoingAU.isDeactivated() || !consumedAU.isDeactivated() && ongoingAU.isDeactivated()) {
+            throw new IllegalCommandException("User accounts can only be merged if they are either both non-deactivated or both deactivated.", this);
```
[the remark this answers is not in the document]
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MergeInAccountCommand.java:67]: Please see above.

File: src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java (hunk 10 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java:235]: I tried putting it there in the postconstruct and couldn't get it to work. So I put it in the engine instead.

File: doc/sphinx-guides/source/api/native-api.rst (hunk 11 above)
[the remark this answers is not in the document]
Comment (scolapasta) [reply doc/sphinx-guides/source/api/native-api.rst:3058]: I agree that "Active" is the opposite of "inactive"; I think of deactivated accounts as inactive, it's just more specific in that it states that they were "deactivated" (how they got to inactive). We probably could have called them "inactive" as well. But changing that now is overkill.

Non-deactivated is wordy and not a good way to describe the the normal state of a user, e.g when you just create one. "I just created an account on Dataverse; it is non-deactivated"

File: src/main/java/edu/harvard/iq/dataverse/DataversePage.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/DataversePage.java:698]: Ah, I see, but a) I also requested simplifying that code and changing it - and it still isn't clear to me why this is only on "create".

File: src/main/java/edu/harvard/iq/dataverse/api/Admin.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/api/Admin.java]: Moved up in 530dab34d.

File: src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java (hunk 10 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java:235]: I don't remember a error. I think it simply didn't work. It had no effect, as I recall.

File: src/main/java/edu/harvard/iq/dataverse/DataversePage.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/DataversePage.java:698]: Because "create" is the action that all authenticated users can take in the root (for prod and various dev environments).

File: src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java (hunk 10 above)
Comment (scolapasta) [reply src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java:235]: That's weird - since it should set the request to point to a GuestUser in that case and therefore fail due to permission. I would prefer this simpler mechanism if we can get it to work, though (and at least understand why it doesn't if it doesn't). Let me go ahead and try it and see what happens.

File: doc/sphinx-guides/source/api/native-api.rst (hunk 11 above)
[the remark this answers is not in the document]
Comment (pdurbin) [reply doc/sphinx-guides/source/api/native-api.rst]: I still prefer the precision but I made the change in df32ec012.

File: src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java (hunk 10 above)
Comment (pdurbin) [reply src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java:235]: Ok. Good luck.

**Review by scolapasta — APPROVED** [review]

**Comment by kcondon** [comment]
Original list:
Issues found so far:

X Disable user endpoint doesn't care what permissions api key has but requires a key, otherwise http 405. Thought, based on discussion in pr and that it is an admin api, that it would not require a key.

X After disabling a user, some existing users cannot be found in assign roles ui, autocomplete. Also will not allow assigning role to fully typed existing user that is not disabled but doesn't appear in autocomplete list. Note other users do appear in auto complete list and the ones that do not appear do appear in dashboard, users. This does not happen on develop branch. Was able to reproduce if users were first created on develop branch and then the last create was disabled. None of the other users appear in assign roles autocomplete. Note that it does not happen if users were created in the disable user branch.
Steps to reproduce:
-on develop branch, create 4 users with similar names: yak1234ab, yak1234bc, yak1234cd, yak1234de.
-on disable user branch, disable user yak1234de
-as dataverse admin, go to dataset permissions page for unpublished draft, type yak, no matches. type yak1234ab no matches,.
-as dataverse admin, go to dashboard, manage users, search on yak, see all users. (this throws an exception at the moment, working that as a separate issue.

Attempting to remove roles using api endpoint with a key that does not have sufficient permissions gives incomplete/confusing error message: {"status":"ERROR","message":"Unable to revoke all roles: null"}

On manage users page, disabled user still appears, can make a superuser. Suggestion, make authentication type for disabled user, disabled.

Disable user if logged in, remains logged in and can edit account info. Update: this happens with delete user too. For disabled case, reenables it but without some stuff, for delete it adds a new account on save!

Can log in using builtin disabled user account, if that disabled user edited their account info in step 5

Can merge the same account into itself with result being user is deleted. In 5.3, throws constraint error, though could use better error msg.

Convert oauth (github) account link/page with same email as a newly created, enabled builtin account results in 500 error:

[2021-03-11T16:35:56.112+0000] [Payara 5.2020.6] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=92 _ThreadName=http-thread-pool::jk-connector(4)] [timeMillis: 1615480556112] [levelValue: 1000] [[
  Error Rendering View[/oauth2/convert.xhtml]
javax.el.ELException: /oauth2/convert.xhtml @23,91 value="#{OAuth2FirstLoginPage.welcomeMessage}": java.lang.NullPointerException

Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.authorization.providers.oauth2.OAuth2FirstLoginPage.getWelcomeMessage(OAuth2FirstLoginPage.java:271)
Convert oauth (github) account with same email as disabled builtin account, sends user to convert account form, then when enter account to convert, provides both a success and failure message and oauth is logged in. Checking account status after shows merge didn't happen.
Convert shib account works with enabled builtin but on disabled builtin, gives both success and failure though it actually fails. Should check and prevent submitting account for conversion as ui above.

Test results:

1. Disable user endpoint doesn't care what permissions api key has but requires a key, otherwise http 405. Thought, based on discussion in pr and that it is an admin api, that it would not require a key.

I can't reproduce this and the automated tests do not use a token. However, the docs were incorrect and showed the use of an API token so I corrected them in abb8be0.

[Kevin] I see the doc was updated to remove the key. However, this is reproducible but after discussing with Gustavo, expected behavior for admin endpoints that assume console log on perms. So, not a bug but doc change removes confusion.

2. After disabling a user, some existing users cannot be found in assign roles ui, autocomplete.
As far as I can tell, autocomplete for assigning roles was completely broken in the branch, due to me botching the query. Fixed in 0efee28.

[Kevin] This is fixed.

3. Attempting to remove roles using api endpoint with a key that does not have sufficient permissions gives incomplete/confusing error message: {"status":"ERROR","message":"Unable to revoke all roles: null"}
The error wasn't being bubbled up from the command. Fixed in 3713104.

On manage users page, disabled user still appears, can make a superuser. Suggestion, make authentication type for disabled user, disabled.
As discussed in Slack, we're putting the word "disabled" in parentheses. In addition the JSON output from /api/admin/list-users now contained "deactivated" and "deactivatedTime". This code and the dashboard code are related. Fixed in c2b7b0a.

Disable user if logged in, remains logged in and can edit account info. Update: this happens with delete user too. For disabled case, reenables it but without some stuff, for delete it adds a new account on save!
Fixed in 3e59e70. Now the getUser code checks if the user in the session still exists and is not disabled.

Concern has been expressed that modifying getUser like this could result in a performance problem. A quick benchmark indicates that if you navigate to the homepage, sign up for an account, and then create a dataverse, the getUser method is called 264 times.

Can log in using builtin disabled user account, if that disabled user edited their account info in step 5
Fixed in 3e59e70, the same getUser fix mentioned above.

Can merge the same account into itself with result being user is deleted. In 5.3, throws constraint error, though could use better error msg.
Indeed, the user was deleted. This bug is probably preexisting in released versions. Fixed in 4f81fbd.

Convert oauth (github) account link/page with same email as a newly created, enabled builtin account results in 500 error:
I can't reproduce this. I'm on 4f81fbd.

Convert oauth (github) account with same email as disabled builtin account, sends user to convert account form, then when enter account to convert, provides both a success and failure message and oauth is logged in. Checking account status after shows merge didn't happen.
Fixed in fbded77 to prevent deactivated accounts from being converted to OAuth accounts.

Convert shib account works with enabled builtin but on disabled builtin, gives both success and failure though it actually fails. Should check and prevent submitting account for conversion as ui above.
Fix in fdc9cbe to prevent deactivated accounts from being converted to Shib accounts.

**Comment by pdurbin** [comment]
> the superuser checkbox is still active

Fixed in c326af4c5. As shown in the screenshot below, the checkbox is disabled for deactivated users. I also enforced this in the underlying command as well as via API.

Screen Shot 2021-03-25 at 4 47 07 PM

**Comment by sekmiller** [comment]
Kevin, I put in an additional test if a user is trying to edit his account info while he is being deleted/deactivated. Hitting save will boot them to the root dv page, and if they try to log in again they will get the bad news.

File: src/main/resources/db/migration/V5.3.0.6__2419-deactivate-users.sql [hunk 15]
```diff
@@ -1,4 +1,6 @@
 -- Users can be deactivated.
 ALTER TABLE authenticateduser ADD COLUMN IF NOT EXISTS deactivated BOOLEAN;
+-- Prevent old users from having null for deactivated.
+UPDATE authenticateduser SET deactivated = false;
```
Comment (scolapasta) [inline src/main/resources/db/migration/V5.3.0.6__2419-deactivate-users.sql:4]: @pdurbin should there be any concern at all if this is run on a db that already has deactivated users (if someone removes this from their flyway table, for example)? Maybe not, but might be safer to add a where clause OR as a default on the Alter table, i.e. 
```
ALTER TABLE authenticateduser ADD COLUMN IF NOT EXISTS deactivated BOOLEAN DEFAULT false
```

File: src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java [hunk 16]
```diff
@@ -284,6 +284,12 @@ public void validateNewPassword(FacesContext context, UIComponent toValidate, Ob
 
     public String save() {
         boolean passwordChanged = false;
+        
+        //First reget user to make sure they weren't deactivated or deleted
+        if (session.getUser().isAuthenticated() && !session.getUser(true).isAuthenticated()) {
+            return "dataverse.xhtml?alias=" + dataverseService.findRootDataverse().getAlias() + "&faces-redirect=true";
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java:290]: why not simplify and just go to homepage, i.e. "/"

File: src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java [hunk 17]
```diff
@@ -284,6 +284,12 @@ public void validateNewPassword(FacesContext context, UIComponent toValidate, Ob
 
     public String save() {
         boolean passwordChanged = false;
+        
+        //First reget user to make sure they weren't deactivated or deleted
+        if (session.getUser().isAuthenticated() && !session.getUser(true).isAuthenticated()) {
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java:289]: is the first part of this needed?

Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java:289]: I guess not. it's left over from when I did the re-get user within the save method.

Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java:289]: no. we need it because if we're creating an account the session user is a guest before they save the new account.

File: src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java (hunk 16 above)
Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java:290]: I can make that change. i was just using the pattern from the bottom of the save method.

Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java:290]: I'm going to leave it as is because when I tried return "/"; it left me in edit mode on the user page which I think would be confusing to the deleted/deactivated user.

File: src/main/resources/db/migration/V5.3.0.6__2419-deactivate-users.sql (hunk 15 above)
Comment (sekmiller) [reply src/main/resources/db/migration/V5.3.0.6__2419-deactivate-users.sql:4]: either works for me. I think "WHERE deactivated IS NULL;" stands out more as intent.
