### PR TITLE
6781 my data render

### LINKED ISSUE #6781: Unable to load "My Data" on production
I have not been able to load My Data in production for several months. 

- Using gmail account

- dvn-cloud-app-1

Kevin got this from the log file:

    [2020-03-31T16:41:41.286-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler]
    [tid: _ThreadID=3520 _ThreadName=jk-connector(107)] [timeMillis: 1585687301286] [levelValue: 1000] [[
    API internal error a04c9666-d233-4158-9d22-147e22bd7ab6: Null Pointer
    java.lang.NullPointerException
    ]]    

    [2020-03-31T16:41:43.683-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.DataverseHeaderFragment] 
    [tid: _ThreadID=3594 _ThreadName=jk-connector(179)] [timeMillis: 1585687303683] [levelValue: 800] [[
    Sending user to = /dataverseuser.xhtml]]

    [2020-03-31T16:41:54.559-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] 
    [tid: _ThreadID=3486 _ThreadName=jk-connector(75)]  [timeMillis: 1585687314559] [levelValue: 900] [[  
    caught IOException trying to open an input stream for worldmap .img file (s3://dvn-cloud:155d1847e11-11f9f553c5ce). 
    Original Error: java.io.IOException: Failed to open auxilary file img for S3 file]]

    [2020-03-31T16:41:55.724-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ServeletExceptionHandler] 
    [tid: _ThreadID=3495 _ThreadName=jk-connector(84)] 
    [timeMillis: 1585687315724] [levelValue: 1000] [[
    API internal error 858adef2-f20d-49ab-84bb-4adbd2eb9857: Null Pointer
    java.lang.NullPointerException
    ]]

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**:
Fixes MyData rendering

**Which issue(s) this PR closes**:

Closes #6781

**Special notes for your reviewer**:
Gets dataset version based on the versionId saved in the SolrSearchResult

**Suggestions on how to test this**:
Cannot be a super user. Also try oddball cases like only a draft and/or all versions deaccessioned.

**Does this PR introduce a user interface change?**:
No

**Is there a release notes update needed for this change?**:
No
**Additional documentation**:
None

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java [hunk 1]
```diff
@@ -560,16 +560,18 @@ public JsonObjectBuilder json(boolean showRelevance, boolean showEntityIds, bool
...
                 nullSafeJsonBuilder.add("storageIdentifier", this.entity.getStorageIdentifier());
                 Dataset ds = (Dataset) this.entity;
-                DatasetVersion dv;
-                if (this.isDraftState()) {
-                    dv = ds.getLatestVersion();
-                } else {
-                    dv = ds.getReleasedVersion();
+                DatasetVersion dv = null;
+
+                for (DatasetVersion v : ds.getVersions()) {
```
Comment (scolapasta) [inline src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java:570]: This is good, but let's move this logic onto a method on Dataset (in case we need to use it elsewhere some time, and then it makes this fewer lines, ie.
DatasetVersion dv = ds.getVersion(this.datasetVersionId);

Comment (sekmiller) [reply src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java]: added the suggested method to Dataset
